import {test,expect,type Page} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve(__dirname, '../../..')+'/';
const evidence=root+'.codex/delivery/evidence/MS-003/MS-003-S04/browser';
mkdirSync(evidence,{recursive:true});
function access(){return JSON.parse(readFileSync(root+'.runtime/development/383a7390af/ms003-s04-browser.json','utf8')) as {workspace:string;email:string;password:string};}
async function login(page:Page,ru=false){const a=access();await page.goto('/auth/sign-in');if(ru)await page.getByRole('button',{name:'Переключить на русский'}).click();await page.getByLabel(ru?'Идентификатор рабочего пространства':'Workspace identifier').fill(a.workspace);await page.getByLabel(ru?'Электронная почта':'Email',{exact:true}).fill(a.email);await page.getByLabel(ru?'Пароль':'Password',{exact:true}).fill(a.password);await page.getByRole('button',{name:ru?'Войти':'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:ru?'Библиотека отчётов':'Report library'})).toBeVisible();}
async function create(page:Page,ru=false){await page.getByRole('link',{name:new RegExp(ru?'Создать отчёт о продажах':'Create sales report')}).click();await expect(page.getByLabel(ru?'Источник':'Source',{exact:true})).not.toHaveValue('');const run=page.waitForResponse((r)=>r.url().includes('/analytics/sales-reports/v1')&&r.request().method()==='POST');await page.getByRole('button',{name:ru?'Применить':'Apply',exact:true}).click();expect((await run).ok()).toBeTruthy();await expect(page.locator('[data-chart-ready=true]')).toBeVisible();const save=page.waitForResponse((r)=>r.url().endsWith('/api/reports/')&&r.request().method()==='POST');await page.getByRole('button',{name:ru?'Сохранить':'Save',exact:true}).click();const response=await save;expect(response.ok()).toBeTruthy();await expect(page).not.toHaveURL(/\/new\/edit/);return response.json();}
for(const ru of [false,true])test(`real journey ${ru?'ru':'en'}`,async({page},info)=>{
  const unexpected:string[]=[];page.on('pageerror',()=>unexpected.push('uncaught page error'));page.on('console',(m)=>{if(m.type()==='error'||m.type()==='warning')unexpected.push('console '+m.type());});page.on('response',(r)=>{if(r.status()>=400)unexpected.push(`${r.status()} ${new URL(r.url()).pathname}`);});
  await login(page,ru);const initial=await create(page,ru);
  await page.getByRole('button',{name:ru?'Доверие к результату':'Result trust',exact:true}).click();await expect(page.getByText('14995 / 15000',{exact:true})).toBeVisible();await expect(page.getByText(ru?'Привязка товарных позиций неполна; итоги по подходящим чекам сохранены.':'Item attribution is incomplete; eligible receipt totals are preserved.',{exact:true})).toBeVisible();
  await page.screenshot({path:`${evidence}/report-${info.project.name}-${ru?'ru':'en'}.png`});
  await page.getByRole('button',{name:ru?'Таблица':'Table',exact:true}).click();await expect(page.locator('tbody tr')).toHaveCount(initial.result.daily.length);await expect(page.locator('tbody tr').first().locator('td').first()).toHaveAttribute('data-value',initial.result.daily[0].net_revenue??'');
  if(info.project.name==='1920'&&ru)await page.screenshot({path:`${evidence}/table-trust-1920-ru.png`});
  const focus=page.getByRole('button',{name:ru?'Развернуть график и таблицу':'Expand chart and table',exact:true});await focus.focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(focus).toBeFocused();
  await page.getByLabel(ru?'С':'From',{exact:true}).fill('2025-02-01');await page.getByLabel(ru?'По':'To',{exact:true}).fill('2025-03-01');await page.getByLabel(ru?'Магазин':'Store',{exact:true}).selectOption({index:1});await page.getByLabel(ru?'Сравнение':'Comparison',{exact:true}).selectOption('previous_year_same_dates');await expect(page.getByRole('button',{name:ru?'Сохранить':'Save',exact:true})).toBeDisabled();
  const calculated=page.waitForResponse((r)=>r.url().includes('/analytics/sales-reports/v1')&&r.request().method()==='POST');await page.getByRole('button',{name:ru?'Применить':'Apply',exact:true}).click();const result=(await calculated).json();await expect(page.getByRole('button',{name:ru?'Сохранить':'Save',exact:true})).toBeEnabled();const savedResponse=page.waitForResponse((r)=>r.url().endsWith('/versions')&&r.request().method()==='POST');await page.getByRole('button',{name:ru?'Сохранить':'Save',exact:true}).click();const saved=await (await savedResponse).json();expect(saved.result.result_id).toBe((await result).result_id);
  let computations=0;page.on('request',(r)=>{if(r.method()==='POST'&&r.url().includes('/analytics/sales-reports/v1'))computations++;});await page.getByRole('link',{name:ru?'Открыть точный предпросмотр':'Open exact draft preview'}).click();await page.reload();await expect(page.locator('[data-chart-ready=true]')).toBeVisible();expect(computations).toBe(0);
  await page.locator('summary').click();await expect(page.getByText('14995 / 15000',{exact:true})).toBeVisible();
  // Browser layout equivalent to 200% desktop zoom: CSS zoom changes layout and paint.
  await page.evaluate(()=>{document.documentElement.style.zoom='2';});await expect(page.getByRole('button',{name:ru?'Таблица':'Table',exact:true})).toBeVisible();await page.getByRole('button',{name:ru?'Таблица':'Table',exact:true}).click();await expect(page.locator('table').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy();await page.screenshot({path:`${evidence}/zoom-${info.project.name}-${ru?'ru':'en'}.png`});expect(unexpected).toEqual([]);
});
test('conflict, exact restart, storage failure, empty result and revoked session',async({page,context,request})=>{
  await login(page);const first=await create(page);const editor=page.url();
  const other=await context.newPage();await other.goto(editor);await expect(other.getByLabel('Report title')).toBeVisible();await other.getByLabel('Report title').fill('Concurrent saved title');await other.getByRole('button',{name:'Save',exact:true}).click();await expect(other.getByText('Saved draft',{exact:true})).toBeVisible();await other.close();
  await page.getByLabel('Report title').fill('Retained unsaved title');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('alert')).toContainText('newer draft');await expect(page.getByLabel('Report title')).toHaveValue('Retained unsaved title');await page.getByRole('button',{name:'Reload saved draft'}).click();await expect(page.getByLabel('Report title')).toHaveValue('Concurrent saved title');
  await page.getByRole('link',{name:'Open exact draft preview'}).click();const exact=page.url();await expect(page.locator('[data-chart-ready=true]')).toBeVisible();
  expect((await request.post('http://127.0.0.1:58105/restart')).ok()).toBeTruthy();await expect.poll(async()=>{try{return (await request.get('/api/health/live')).status();}catch{return 0;}}).toBe(200);await page.reload();await expect(page.locator('[data-chart-ready=true]')).toBeVisible();
  const sid=new URL(exact).pathname.split('/')[6];expect((await request.post(`http://127.0.0.1:58105/artifact/${sid}/storage`)).ok()).toBeTruthy();try{await page.reload();await expect(page.getByRole('alert')).toContainText('unavailable');await expect(page.locator('.report-metrics')).toHaveCount(0);}finally{expect((await request.post(`http://127.0.0.1:58105/artifact/${sid}/restore`)).ok()).toBeTruthy();}
  await page.goto(editor);await page.getByLabel('From',{exact:true}).fill('2023-01-01');await page.getByLabel('To',{exact:true}).fill('2023-01-02');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByText('No eligible receipts in this period.')).toBeVisible();
  const revoked=await page.evaluate(async()=>{const csrf=decodeURIComponent(document.cookie.split('; ').find((s)=>s.startsWith('custometry_csrf='))!.split('=')[1]);const list=await (await fetch('/api/identity/sessions')).json();const session=list.sessions.find((s:{device_label:string;revoked:boolean})=>s.device_label==='report-workspace'&&!s.revoked);const response=await fetch('/api/identity/sessions/'+session.id,{method:'DELETE',headers:{'X-CSRF-Token':csrf}});return response.status;});expect(revoked).toBe(204);await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByRole('alert')).toContainText('session expired');await expect(page.locator('.report-metrics')).toHaveCount(0);await expect(page.locator('table')).toHaveCount(0);
});
test('preserved pilot normalized capture',async({page},info)=>{await page.goto('http://127.0.0.1:8834/ru/source.html');await page.locator('#context-open').click();await page.locator('[data-inspector-tab=trust]').click();await page.screenshot({path:`${evidence}/pilot-${info.project.name}.png`});});

test('draft history, exact locator and expired session',async({page,request})=>{
  await login(page);const saved=await create(page);const editor=page.url();const title='Draft retained '+saved.report_id;
  await page.getByLabel('Report title').fill(title);
  await page.goBack();await page.goForward();
  await expect(page.getByLabel('Report title')).toHaveValue(title);
  await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByText('Saved draft',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Reports',exact:true}).first().click();
  await page.getByRole('link',{name:title,exact:true}).last().click();
  await expect(page.getByLabel('Report title')).toHaveValue(title);
  await page.getByRole('link',{name:'Open exact draft preview'}).click();const exact=page.url();
  await page.goto(exact+'&focus='+saved.composition.blocks.find((b:{block_type:string})=>b.block_type==='chart').block_id);
  await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Close Focus',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.goto(exact.replace(/page=[^&]+/,'page=invalid'));await expect(page.getByRole('alert')).toContainText('unavailable');await expect(page.locator('.report-metrics')).toHaveCount(0);
  await page.goto(editor);await expect(page.locator('[data-chart-ready=true]')).toBeVisible();
  expect((await request.post('http://127.0.0.1:58105/expire')).ok()).toBeTruthy();await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByRole('alert')).toContainText('session expired');await expect(page.locator('.report-metrics')).toHaveCount(0);
});
