export const reportPilotCopy = {
  "en": {
    "context": "Context",
    "filters": "Filters",
    "discussion": "Discussion",
    "trust": "Trust",
    "views": "Views",
    "notAvailableInThisReport": "Not available in this report",
    "comments": "Comments",
    "reportPages": "Report pages",
    "dynamics": "Dynamics",
    "segments": "Segments",
    "notesMethodology": "Notes & methodology",
    "reportControls": "Report controls",
    "period": "Period",
    "day": "Day",
    "reportAppearance": "Report appearance",
    "analyticalTextSize": "Analytical text size",
    "language": "Русский",
    "reportView": "Report view",
    "completedReceiptsEurDaily": "Completed receipts · EUR · daily",
    "customizeKpi": "Customize KPI",
    "blockPeriod": "Block period",
    "blockComparison": "Block comparison",
    "blockGrouping": "Block grouping",
    "dataView": "Data view",
    "chartSettings": "Chart settings",
    "downloadChart": "Download chart",
    "reportInspector": "Report inspector",
    "contextActionsAndTrust": "Context, actions and trust",
    "inspectorSections": "Inspector sections",
    "onThisPage": "On this page",
    "report": "Report",
    "freshnessAndCoverage": "Freshness and coverage",
    "close": "Close",
    "exactValuesBelowTheChartWithoutSwitchingModes": "Exact values below the chart, without switching modes",
    "skipToReport": "Skip to report",
    "navigation": "Navigation",
    "searchIsNotAvailable": "Search is not available",
    "search": "Search",
    "notifications": "Notifications",
    "closeSectionMenu": "Close section menu",
    "signOut": "Sign out",
    "reportHelp": "Report help",
    "reports": "Reports",
    "home": "Home"
  },
  "ru": {
    "context": "Контекст",
    "filters": "Фильтры",
    "discussion": "Обсуждение",
    "trust": "Доверие",
    "views": "Виды",
    "notAvailableInThisReport": "Недоступно в этом отчёте",
    "comments": "Комментарии",
    "reportPages": "Страницы отчёта",
    "dynamics": "Динамика",
    "segments": "Сегменты",
    "notesMethodology": "Заметки и методика",
    "reportControls": "Параметры отчёта",
    "period": "Период",
    "day": "День",
    "reportAppearance": "Оформление аналитических данных",
    "analyticalTextSize": "Размер аналитических данных",
    "language": "English",
    "reportView": "Вид отчёта",
    "completedReceiptsEurDaily": "Завершённые чеки · EUR · по дням",
    "customizeKpi": "Настроить KPI",
    "blockPeriod": "Период блока",
    "blockComparison": "Сравнение блока",
    "blockGrouping": "Группировка блока",
    "dataView": "Представление данных",
    "chartSettings": "Настройки графика",
    "downloadChart": "Скачать график",
    "reportInspector": "Инспектор отчёта",
    "contextActionsAndTrust": "Контекст, действия и доверие",
    "inspectorSections": "Разделы инспектора",
    "onThisPage": "На этой странице",
    "report": "Отчёт",
    "freshnessAndCoverage": "Свежесть и покрытие",
    "close": "Закрыть",
    "exactValuesBelowTheChartWithoutSwitchingModes": "Точные значения ниже графика — без переключения режима",
    "skipToReport": "Перейти к отчёту",
    "navigation": "Навигация",
    "searchIsNotAvailable": "Поиск пока недоступен",
    "search": "Поиск",
    "notifications": "Уведомления",
    "closeSectionMenu": "Закрыть меню раздела",
    "signOut": "Выйти",
    "reportHelp": "Работа с отчётом",
    "reports": "Отчёты",
    "home": "Главная"
  }
} as const;
