// Generated by custometry-foundation-openapi-ts v1. Do not edit.
export const contractSourceDigest = "91be62f618352e82e6c1b605570545b145ef261df0437249eb7747bbaca0ac07" as const;
export const externalJsonSchemaIds = [] as const;

export interface AnalyticsResultListResponse {
  readonly results: ReadonlyArray<AnalyticsResultResponse>;
  readonly visible_count: number;
}

export interface AnalyticsResultResponse {
  readonly applied_comparison_mode: string;
  readonly calendar_version_id: string;
  readonly comparability_status: "comparable" | "partial" | "not_comparable";
  readonly comparison_coverage: Record<string, unknown> | null;
  readonly comparison_policy_hash: string;
  readonly current_coverage: Record<string, unknown>;
  readonly freshness: Record<string, unknown>;
  readonly limitation_codes: ReadonlyArray<string>;
  readonly lineage: Record<string, unknown>;
  readonly manifest: Record<string, unknown>;
  readonly metric_groups: ReadonlyArray<MetricGroupProjection>;
  readonly normalized_filter_expression_hash: string;
  readonly policy_hash: string;
  readonly quality: Record<string, unknown>;
  readonly request_hash: string;
  readonly resolved_comparison_period: Record<string, unknown> | null;
  readonly resolved_current_period: Record<string, unknown>;
  readonly result_id: string;
  readonly result_type: "sales" | "customer" | "rfm";
  readonly rfm_profiles: ReadonlyArray<Record<string, unknown>>;
  readonly semantic_dataset_version_id: string;
  readonly timezone: string;
}

export interface AnalyticsRunRequest {
  readonly comparison: TimeComparisonRequest;
  readonly filters?: ReadonlyArray<TypedFilterRequest>;
  readonly result_type: "sales" | "customer" | "rfm";
  readonly rfm_frequency_measure?: "receipt_count" | "purchase_day_count";
  readonly rfm_score_bins?: number;
  readonly rfm_segment_rule_set_version?: "rfm-retail-v1";
  readonly semantic_dataset_version_id: string;
}

export interface Comparison {
  readonly coverage: Coverage;
  readonly daily: ReadonlyArray<Daily>;
  readonly period: Record<string, unknown>;
  readonly totals: Totals;
}

export interface Coverage {
  readonly calendar_days: number;
  readonly declared_complete_days: number;
  readonly observed_receipt_days: number;
  readonly period_days: number;
  readonly status: "complete" | "partial" | "missing";
}

export interface Daily {
  readonly average_receipt: string | null;
  readonly date: string;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
  readonly state: "missing_calendar" | "incomplete" | "observed" | "no_eligible_receipts" | "comparison_unavailable";
}

export interface HTTPValidationError {
  readonly detail?: ReadonlyArray<ValidationError>;
}

export interface MetricGroupProjection {
  readonly group_id: string;
  readonly group_order: number;
  readonly metrics: ReadonlyArray<MetricProjection>;
}

export interface MetricProjection {
  readonly absolute_change: string | null;
  readonly compact_comparison: string | null;
  readonly compact_current: string | null;
  readonly comparison_value: string | null;
  readonly current_value: string | null;
  readonly limitation_codes: ReadonlyArray<string>;
  readonly metric_id: string;
  readonly metric_order: number;
  readonly percent_change: string | null;
}

export interface PeriodRequest {
  readonly ends_on: string;
  readonly starts_on: string;
}

export interface SalesResponse {
  readonly changes: Record<string, unknown>;
  readonly comparability_status: "comparable" | "not_comparable";
  readonly comparison: Comparison | null;
  readonly coverage: Coverage;
  readonly daily: ReadonlyArray<Daily>;
  readonly lineage: Record<string, unknown>;
  readonly manifest: Record<string, unknown>;
  readonly mart: Record<string, unknown>;
  readonly metrics: ReadonlyArray<Record<string, unknown>>;
  readonly parameters: Record<string, unknown>;
  readonly policy_hash: string;
  readonly request_hash: string;
  readonly result_id: string;
  readonly schema_version: "sales-report/v1";
  readonly semantic_dataset_version_id: string;
  readonly totals: Totals;
  readonly trust: Record<string, unknown>;
}

export interface SalesRunRequest {
  readonly comparison?: "none" | "previous_year_same_dates";
  readonly ends_on?: string;
  readonly semantic_dataset_version_id: string;
  readonly starts_on?: string;
  readonly store_id?: string | null;
}

export interface TimeComparisonRequest {
  readonly calendar_version_id: string;
  readonly comparison_period?: PeriodRequest | null;
  readonly current_period: PeriodRequest;
  readonly definition_compatibility_policy: "require_same_versions" | "allow_explicit_rebase";
  readonly incomplete_period_policy: "exclude" | "comparable_elapsed_days" | "explicit_partial";
  readonly iso_week_53_policy: "calendar_map" | "exclude" | "explicit_partial";
  readonly leap_day_policy: "calendar_map" | "exclude" | "merge_with_feb_28";
  readonly mode: "none" | "previous_year_same_dates" | "previous_year_calendar_aligned" | "previous_year_iso_week_aligned" | "previous_year_fiscal_period" | "previous_year_comparable_elapsed_days";
  readonly timezone: string;
}

export interface Totals {
  readonly average_receipt: string | null;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
}

export interface TypedFilterRequest {
  readonly field: "store_id" | "channel_id" | "currency" | "status" | "net_amount";
  readonly operator: "eq" | "in" | "gte" | "lte";
  readonly value: string | number | string | ReadonlyArray<string>;
}

export interface ValidationError {
  readonly loc: ReadonlyArray<string | number>;
  readonly msg: string;
  readonly type: string;
}

export class SalesReportClient {
  public constructor(private readonly baseUrl: string, private readonly fetcher: typeof fetch = globalThis.fetch.bind(globalThis)) {}
  public async run(input: SalesRunRequest, csrfToken: string): Promise<SalesResponse> {
    const response = await this.fetcher(`${this.baseUrl}/sales-reports/v1`, {
      method: "POST", credentials: "same-origin",
      headers: {"Content-Type": "application/json", "X-CSRF-Token": csrfToken},
      body: JSON.stringify(input),
    });
    if (!response.ok) throw new Error(`SALES_REPORT_HTTP_${response.status}`);
    return response.json() as Promise<SalesResponse>;
  }
  public async get(resultId: string): Promise<SalesResponse> {
    const response = await this.fetcher(`${this.baseUrl}/sales-reports/v1/${encodeURIComponent(resultId)}`, {credentials: "same-origin"});
    if (!response.ok) throw new Error(`SALES_REPORT_HTTP_${response.status}`);
    return response.json() as Promise<SalesResponse>;
  }
}
