// Generated by custometry-foundation-openapi-ts v1. Do not edit.
export const contractSourceDigest = "f368d40ba87360dac4830af3471388c5bbce7439dd70ac7ec3be6211b9c0a8b1" as const;
export const externalJsonSchemaIds = [] as const;

export interface AnalyticsResultListResponse {
  readonly results: ReadonlyArray<AnalyticsResultResponse>;
  readonly visible_count: number;
}

export interface AnalyticsResultResponse {
  readonly applied_comparison_mode: string;
  readonly calendar_version_id: string;
  readonly comparability_status: "comparable" | "partial" | "not_comparable";
  readonly comparison_coverage: Record<string, unknown> | null;
  readonly comparison_policy_hash: string;
  readonly current_coverage: Record<string, unknown>;
  readonly freshness: Record<string, unknown>;
  readonly limitation_codes: ReadonlyArray<string>;
  readonly lineage: Record<string, unknown>;
  readonly manifest: Record<string, unknown>;
  readonly metric_groups: ReadonlyArray<MetricGroupProjection>;
  readonly normalized_filter_expression_hash: string;
  readonly policy_hash: string;
  readonly quality: Record<string, unknown>;
  readonly request_hash: string;
  readonly resolved_comparison_period: Record<string, unknown> | null;
  readonly resolved_current_period: Record<string, unknown>;
  readonly result_id: string;
  readonly result_type: "sales" | "customer" | "rfm";
  readonly rfm_profiles: ReadonlyArray<Record<string, unknown>>;
  readonly semantic_dataset_version_id: string;
  readonly timezone: string;
}

export interface AnalyticsRunRequest {
  readonly comparison: TimeComparisonRequest;
  readonly filters?: ReadonlyArray<TypedFilterRequest>;
  readonly result_type: "sales" | "customer" | "rfm";
  readonly rfm_frequency_measure?: "receipt_count" | "purchase_day_count";
  readonly rfm_score_bins?: number;
  readonly rfm_segment_rule_set_version?: "rfm-retail-v1";
  readonly semantic_dataset_version_id: string;
}

export interface ArtifactRef {
  readonly artifact_id: string;
  readonly content_hash: string;
}

export interface CalendarRef {
  readonly content_hash: string;
  readonly version_id: string;
}

export interface CardComparisonV1 {
  readonly buckets: ReadonlyArray<ComparisonBucket>;
  readonly comparability_status: "comparable" | "descriptive" | "unavailable";
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly left: ComparisonSide;
  readonly manifest: ArtifactRef;
  readonly mode: "temporal" | "pair";
  readonly right: ComparisonSide;
  readonly schema_version: "card-comparison/v1";
  readonly totals: ComparisonValues;
}

export interface CardResultBinding {
  readonly bucket_projection: "net_revenue" | "receipt_count" | "average_receipt";
  readonly card_id: string;
  readonly configuration_hash: string;
  readonly effective_context_hash: string;
  readonly format: NumberFormat;
  readonly metric_ref: MetricRef;
  readonly readiness: "ready" | "no_data" | "comparison_unavailable";
  readonly result: ResultRef;
  readonly unit: "EUR" | "receipt" | "EUR/receipt";
}

export interface CompareRequest {
  readonly left: CardResultBinding;
  readonly right: CardResultBinding | null;
  readonly semantic_dataset_version_id: string;
}

export interface Comparison {
  readonly coverage: custometry_api__analytics__sales_models__Coverage;
  readonly daily: ReadonlyArray<Daily>;
  readonly period: Record<string, unknown>;
  readonly totals: Totals;
}

export interface ComparisonBucket {
  readonly absolute_delta: string | null;
  readonly bucket_id: string;
  readonly left: string | null;
  readonly left_coverage: packages__contracts__analytics__workspace__Coverage;
  readonly reason_codes: ReadonlyArray<string>;
  readonly relative_delta_percent: string | null;
  readonly right: string | null;
  readonly right_coverage: packages__contracts__analytics__workspace__Coverage;
}

export interface ComparisonSide {
  readonly baseline_dates: ReadonlyArray<string> | null;
  readonly card_id: string;
  readonly context: EffectiveContext;
  readonly format: NumberFormat;
  readonly metric_ref: MetricRef;
  readonly result: ResultRef;
  readonly unit: "EUR" | "receipt" | "EUR/receipt";
}

export interface ComparisonValues {
  readonly absolute_delta: string | null;
  readonly left: string | null;
  readonly left_coverage: packages__contracts__analytics__workspace__Coverage;
  readonly reason_codes: ReadonlyArray<string>;
  readonly relative_delta_percent: string | null;
  readonly right: string | null;
  readonly right_coverage: packages__contracts__analytics__workspace__Coverage;
}

export interface Daily {
  readonly average_receipt: string | null;
  readonly date: string;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
  readonly state: "missing_calendar" | "incomplete" | "observed" | "no_eligible_receipts" | "comparison_unavailable";
}

export interface DatasetOption {
  readonly id: string;
  readonly label: string;
  readonly stores: ReadonlyArray<StoreOption>;
  readonly version: number;
}

export interface DayAlignment {
  readonly baseline_date: string | null;
  readonly current_date: string;
}

export interface EffectiveContext {
  readonly alignment: "none" | "previous_year_same_dates";
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly ends_on: string;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly starts_on: string;
  readonly store_ids: ReadonlyArray<string>;
  readonly timezone?: "UTC";
  readonly week_start?: "monday";
}

export interface HTTPValidationError {
  readonly detail?: ReadonlyArray<ValidationError>;
}

export interface MetricGroupProjection {
  readonly group_id: string;
  readonly group_order: number;
  readonly metrics: ReadonlyArray<MetricProjection>;
}

export interface MetricProjection {
  readonly absolute_change: string | null;
  readonly compact_comparison: string | null;
  readonly compact_current: string | null;
  readonly comparison_value: string | null;
  readonly current_value: string | null;
  readonly limitation_codes: ReadonlyArray<string>;
  readonly metric_id: string;
  readonly metric_order: number;
  readonly percent_change: string | null;
}

export interface MetricRef {
  readonly content_hash: string;
  readonly metric_id: "net_revenue" | "receipt_count" | "average_receipt";
  readonly version_id: string;
}

export interface MetricValues {
  readonly average_receipt: string | null;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
}

export interface NumberFormat {
  readonly decimal_places: number;
}

export interface PeriodRequest {
  readonly ends_on: string;
  readonly starts_on: string;
}

export interface QueryContext {
  readonly ends_on: string;
  readonly starts_on: string;
  readonly store_ids: ReadonlyArray<string> | null;
}

export interface ResultRef {
  readonly manifest: ArtifactRef;
  readonly result_id: string;
  readonly schema_version: "metric-workspace/v2";
}

export interface SalesContext {
  readonly datasets: ReadonlyArray<DatasetOption>;
  readonly default_period: Record<string, unknown>;
  readonly eligibility: Record<string, unknown>;
  readonly schema_version: "sales-report-context/v1";
  readonly workspace_id: string;
}

export interface SalesResponse {
  readonly changes: Record<string, unknown>;
  readonly comparability_status: "comparable" | "not_comparable";
  readonly comparison: Comparison | null;
  readonly coverage: custometry_api__analytics__sales_models__Coverage;
  readonly daily: ReadonlyArray<Daily>;
  readonly lineage: Record<string, unknown>;
  readonly manifest: Record<string, unknown>;
  readonly mart: Record<string, unknown>;
  readonly metrics: ReadonlyArray<Record<string, unknown>>;
  readonly parameters: Record<string, unknown>;
  readonly policy_hash: string;
  readonly request_hash: string;
  readonly result_id: string;
  readonly schema_version: "sales-report/v1";
  readonly semantic_dataset_version_id: string;
  readonly totals: Totals;
  readonly trust: Record<string, unknown>;
}

export interface SalesRunRequest {
  readonly comparison?: "none" | "previous_year_same_dates";
  readonly ends_on?: string;
  readonly semantic_dataset_version_id: string;
  readonly starts_on?: string;
  readonly store_id?: string | null;
}

export interface StoreOption {
  readonly id: string;
  readonly label: string;
}

export interface TemporalBucket {
  readonly baseline_dates: ReadonlyArray<string>;
  readonly bucket_id: string;
  readonly changes: Record<string, unknown>;
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly values: MetricValues;
}

export interface TemporalProjection {
  readonly alignment: "previous_year_same_dates";
  readonly baseline_dates: ReadonlyArray<string>;
  readonly buckets: ReadonlyArray<TemporalBucket>;
  readonly changes: Record<string, unknown>;
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly excluded_baseline_dates: ReadonlyArray<string>;
  readonly mapping: ReadonlyArray<DayAlignment>;
  readonly reason_codes: ReadonlyArray<string>;
  readonly totals: MetricValues;
}

export interface TimeComparisonRequest {
  readonly calendar_version_id: string;
  readonly comparison_period?: PeriodRequest | null;
  readonly current_period: PeriodRequest;
  readonly definition_compatibility_policy: "require_same_versions" | "allow_explicit_rebase";
  readonly incomplete_period_policy: "exclude" | "comparable_elapsed_days" | "explicit_partial";
  readonly iso_week_53_policy: "calendar_map" | "exclude" | "explicit_partial";
  readonly leap_day_policy: "calendar_map" | "exclude" | "merge_with_feb_28";
  readonly mode: "none" | "previous_year_same_dates" | "previous_year_calendar_aligned" | "previous_year_iso_week_aligned" | "previous_year_fiscal_period" | "previous_year_comparable_elapsed_days";
  readonly timezone: string;
}

export interface Totals {
  readonly average_receipt: string | null;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
}

export interface TypedFilterRequest {
  readonly field: "store_id" | "channel_id" | "currency" | "status" | "net_amount";
  readonly operator: "eq" | "in" | "gte" | "lte";
  readonly value: string | number | string | ReadonlyArray<string>;
}

export interface ValidationError {
  readonly loc: ReadonlyArray<string | number>;
  readonly msg: string;
  readonly type: string;
}

export interface WorkspaceBucket {
  readonly bucket_end_exclusive: string;
  readonly bucket_id: string;
  readonly bucket_start: string;
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly clipped: boolean;
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly effective_end_exclusive: string;
  readonly effective_ends_on: string;
  readonly effective_start: string;
  readonly effective_starts_on: string;
  readonly fiscal_half: number | null;
  readonly fiscal_quarter: number | null;
  readonly fiscal_year: number | null;
  readonly is_partial_bucket: boolean;
  readonly label: string;
  readonly natural_ends_on: string;
  readonly natural_starts_on: string;
  readonly state: "ready" | "no_data" | "incomplete";
  readonly values: MetricValues;
}

export interface WorkspaceDay {
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly date: string;
  readonly values: MetricValues;
}

export interface WorkspaceLineage {
  readonly data_as_of: string;
  readonly metric_components: ReadonlyArray<MetricRef>;
  readonly source_artifacts: ReadonlyArray<ArtifactRef>;
  readonly source_calendar_version_id: string;
}

export interface WorkspaceResultV2 {
  readonly buckets: ReadonlyArray<WorkspaceBucket>;
  readonly comparison: CardComparisonV1 | null;
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly daily: ReadonlyArray<WorkspaceDay>;
  readonly effective_context: EffectiveContext;
  readonly lineage: WorkspaceLineage;
  readonly manifest: ArtifactRef;
  readonly metric_refs: ReadonlyArray<MetricRef>;
  readonly policy_hash: string;
  readonly publication_hash: string;
  readonly request_hash: string;
  readonly result_id: string;
  readonly schema_version: "metric-workspace/v2";
  readonly semantic_dataset_version_id: string;
  readonly temporal: TemporalProjection | null;
  readonly totals: MetricValues;
  readonly trust: WorkspaceTrust;
}

export interface WorkspaceRunRequest {
  readonly alignment: "none" | "previous_year_same_dates";
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly common: QueryContext;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly local_store_ids: ReadonlyArray<string> | null;
  readonly metric_refs: ReadonlyArray<MetricRef>;
  readonly semantic_dataset_version_id: string;
}

export interface WorkspaceTrust {
  readonly reason_codes: ReadonlyArray<string>;
  readonly status: "ready" | "no_data" | "comparison_unavailable";
}

export interface custometry_api__analytics__sales_models__Coverage {
  readonly calendar_days: number;
  readonly declared_complete_days: number;
  readonly observed_receipt_days: number;
  readonly period_days: number;
  readonly status: "complete" | "partial" | "missing";
}

export interface packages__contracts__analytics__workspace__Coverage {
  readonly calendar_days: number;
  readonly declared_complete_days: number;
  readonly eligible_receipts: number;
  readonly expected_days: number;
  readonly observed_days: number;
  readonly reason_codes: ReadonlyArray<string>;
  readonly state: "complete" | "partial" | "unavailable";
}

export class SalesReportClient {
  public constructor(private readonly baseUrl: string, private readonly fetcher: typeof fetch = globalThis.fetch.bind(globalThis)) {}
  public async run(input: SalesRunRequest, csrfToken: string): Promise<SalesResponse> {
    const response = await this.fetcher(`${this.baseUrl}/sales-reports/v1`, {
      method: "POST", credentials: "same-origin",
      headers: {"Content-Type": "application/json", "X-CSRF-Token": csrfToken},
      body: JSON.stringify(input),
    });
    if (!response.ok) throw new Error(`SALES_REPORT_HTTP_${response.status}`);
    return response.json() as Promise<SalesResponse>;
  }
  public async get(resultId: string): Promise<SalesResponse> {
    const response = await this.fetcher(`${this.baseUrl}/sales-reports/v1/${encodeURIComponent(resultId)}`, {credentials: "same-origin"});
    if (!response.ok) throw new Error(`SALES_REPORT_HTTP_${response.status}`);
    return response.json() as Promise<SalesResponse>;
  }
}
