// Generated by custometry-foundation-openapi-ts v1. Do not edit.
export const contractSourceDigest = "090f5634cfb4b77ef01403e4b4bfc546544e31749133545f5f36c8c95e2c8663" as const;
export const externalJsonSchemaIds = ["https://custometry.local/schemas/foundation-health.schema.json","https://custometry.local/schemas/route-registry.schema.json"] as const;

export interface HealthResponse {
  readonly code?: string | null;
  readonly service: "api";
  readonly status: "ok" | "ready" | "not_ready";
  readonly version: string;
}

export interface VersionResponse {
  readonly service: "api";
  readonly version: string;
}

export class FoundationApiClient {
  public constructor(
    private readonly baseUrl: string,
    private readonly fetcher: typeof fetch = globalThis.fetch.bind(globalThis),
  ) {}

  public async live_health_live_get(): Promise<HealthResponse> {
    const response = await this.fetcher(`${this.baseUrl}/health/live`, { method: "GET" });
    if (!response.ok) throw new Error("live_health_live_get failed");
    return (await response.json()) as HealthResponse;
  }

  public async ready_health_ready_get(): Promise<HealthResponse> {
    const response = await this.fetcher(`${this.baseUrl}/health/ready`, { method: "GET" });
    if (!response.ok) throw new Error("ready_health_ready_get failed");
    return (await response.json()) as HealthResponse;
  }

  public async version_version_get(): Promise<VersionResponse> {
    const response = await this.fetcher(`${this.baseUrl}/version`, { method: "GET" });
    if (!response.ok) throw new Error("version_version_get failed");
    return (await response.json()) as VersionResponse;
  }

}
