// Generated by custometry-foundation-openapi-ts v1. Do not edit.
export const contractSourceDigest = "4d6c442a1584aff9c43ea093b26495c04c856af341b211ac0c248821eb3b38ef" as const;
export const externalJsonSchemaIds = [] as const;

export interface AnalyticalDocumentCompositionV1 {
  readonly access_policy_id: string;
  readonly analytical_document_id: string;
  readonly analytical_document_version_id: string;
  readonly blocks: ReadonlyArray<Block>;
  readonly brand_profile_version_id: string;
  readonly chapters: ReadonlyArray<Record<string, unknown>>;
  readonly composition_schema_version: 1;
  readonly default_page_id: string;
  readonly filter_scope_bindings: ReadonlyArray<Record<string, unknown>>;
  readonly navigation_mode: "tabs";
  readonly pages: ReadonlyArray<Page>;
  readonly profile: "workbook_report";
  readonly sections: ReadonlyArray<Section>;
  readonly source_owner_ref: Record<string, unknown>;
  readonly workspace_id: string;
}

export interface Block {
  readonly block_id: string;
  readonly block_type: "metric_group" | "chart" | "table" | "result_trust";
  readonly content_binding?: null;
  readonly order: number;
  readonly presentation: Record<string, unknown>;
  readonly section_id: string;
  readonly source_binding: Record<string, unknown>;
}

export interface BrandProfileObject {
  readonly kind: "brand_profile";
  readonly payload: SystemBrandProfileV1;
  readonly reference: Reference;
}

export interface ChartSpecObject {
  readonly kind: "chart_spec";
  readonly payload: LineChartSpecV1;
  readonly reference: Reference;
}

export interface CompanyPackObject {
  readonly kind: "company_pack";
  readonly payload: SystemCompanyPackV1;
  readonly reference: Reference;
}

export interface DraftResponse {
  readonly author_principal_id: string;
  readonly composition: AnalyticalDocumentCompositionV1;
  readonly contract_version: "draft-report/v1";
  readonly lifecycle: "owned_draft_preview";
  readonly manifest: Record<string, unknown>;
  readonly page_snapshot: Record<string, unknown>;
  readonly references: PreparedResponse;
  readonly report_id: string;
  readonly result: Record<string, unknown>;
  readonly revision: number;
  readonly saved_at: string;
  readonly snapshot: Record<string, unknown>;
  readonly snapshot_id: string;
  readonly title: string;
  readonly version_id: string;
}

export interface HTTPValidationError {
  readonly detail?: ReadonlyArray<ValidationError>;
}

export interface LineChartSpecV1 {
  readonly access_policy: Record<string, unknown>;
  readonly accessibility: Record<string, unknown>;
  readonly annotations: ReadonlyArray<Record<string, unknown>>;
  readonly axes: ReadonlyArray<Record<string, unknown>>;
  readonly chart_data: Record<string, unknown>;
  readonly chart_spec_id: string;
  readonly chart_type: "line";
  readonly created_at: string;
  readonly description_key: null;
  readonly dimensions: ReadonlyArray<Record<string, unknown>>;
  readonly export_policy: Record<string, unknown>;
  readonly interaction: Record<string, unknown>;
  readonly measures: ReadonlyArray<Record<string, unknown>>;
  readonly range_timeline: null;
  readonly schema_version: "1.0.0";
  readonly series: ReadonlyArray<Record<string, unknown>>;
  readonly source_binding: Record<string, unknown>;
  readonly title_key: string;
  readonly title_override: null;
  readonly visual_semantics: Record<string, unknown>;
  readonly workspace_id: string;
}

export interface Page {
  readonly chapter_id?: null;
  readonly layout_mode: "flow";
  readonly order: number;
  readonly page_id: string;
  readonly title: Record<string, unknown>;
  readonly visibility: "visible";
}

export interface PrepareRequest {
  readonly contract_version: "draft-report/v1";
  readonly result_id: string;
}

export interface PreparedResponse {
  readonly brand_profile: BrandProfileObject;
  readonly chart_spec: ChartSpecObject;
  readonly company_pack: CompanyPackObject;
  readonly contract_version: "draft-report/v1";
}

export interface Reference {
  readonly content_hash: string;
  readonly id: string;
}

export interface ReportList {
  readonly reports: ReadonlyArray<ReportSummary>;
  readonly visible_count: number;
}

export interface ReportSummary {
  readonly lifecycle: "owned_draft_preview";
  readonly report_id: string;
  readonly revision: number;
  readonly saved_at: string;
  readonly snapshot_id: string;
  readonly title: string;
  readonly version_id: string;
}

export interface SaveRequest {
  readonly brand_profile: Reference;
  readonly chart_spec: Reference;
  readonly company_pack: Reference;
  readonly contract_version: "draft-report/v1";
  readonly expected_revision: number;
  readonly idempotency_key: string;
  readonly result_id: string;
  readonly title: string;
}

export interface Section {
  readonly order: number;
  readonly page_id: string;
  readonly parent_section_id?: null;
  readonly section_id: string;
  readonly title?: null;
}

export interface SystemBrandProfileV1 {
  readonly brand_profile_version_id: string;
  readonly font_family: "Inter";
  readonly name: string;
  readonly remote_assets: ReadonlyArray<string>;
  readonly schema_version: "system-brand/v1";
  readonly source: Record<string, unknown>;
  readonly themes: ReadonlyArray<"abyss" | "graphite" | "frost" | "paper">;
  readonly token_version: string;
  readonly tokens: ReadonlyArray<Record<string, unknown>>;
}

export interface SystemCompanyPackV1 {
  readonly brand_profile: Reference;
  readonly company_pack_version_id: string;
  readonly localization_catalogs: ReadonlyArray<"en" | "ru">;
  readonly methodology_packs: ReadonlyArray<Record<string, unknown>>;
  readonly metric_versions: ReadonlyArray<Record<string, unknown>>;
  readonly name: string;
  readonly schema_version: "system-company-pack/v1";
}

export interface ValidationError {
  readonly loc: ReadonlyArray<string | number>;
  readonly msg: string;
  readonly type: string;
}

export class DraftReportClient {
  public constructor(private readonly baseUrl: string, private readonly fetcher: typeof fetch = globalThis.fetch.bind(globalThis)) {}
  private async request<T>(path: string, input?: unknown, csrfToken?: string): Promise<T> {
    const response = await this.fetcher(`${this.baseUrl}${path}`, {
      method: input === undefined ? "GET" : "POST", credentials: "same-origin", cache: "no-store",
      headers: input === undefined ? {} : {"Content-Type": "application/json", "X-CSRF-Token": csrfToken ?? ""},
      ...(input === undefined ? {} : {body: JSON.stringify(input)}),
    });
    if (!response.ok) {
      const error = await response.json() as {code?: string};
      throw new Error(error.code ?? `DRAFT_REPORT_HTTP_${response.status}`);
    }
    return response.json() as Promise<T>;
  }
  public prepare(input: PrepareRequest, csrf: string): Promise<PreparedResponse> { return this.request("/prepare", input, csrf); }
  public create(input: SaveRequest, csrf: string): Promise<DraftResponse> { return this.request("/", input, csrf); }
  public save(id: string, input: SaveRequest, csrf: string): Promise<DraftResponse> { return this.request(`/${encodeURIComponent(id)}/versions`, input, csrf); }
  public get(id: string): Promise<DraftResponse> { return this.request(`/${encodeURIComponent(id)}`); }
  public preview(id: string, snapshot: string, locator: Record<string, string> = {}): Promise<DraftResponse> { const query = new URLSearchParams(locator); return this.request(`/${encodeURIComponent(id)}/snapshots/${encodeURIComponent(snapshot)}${query.size ? "?" + query.toString() : ""}`); }
  public list(offset = 0, limit = 50): Promise<ReportList> { return this.request(`/?offset=${offset}&limit=${limit}`); }
}
