// Generated by custometry-foundation-openapi-ts v1. Do not edit.
export const contractSourceDigest = "a79ea0f0865093b9e470509873a41dad80090a1f186c2becbad986a6b1f46ba9" as const;
export const externalJsonSchemaIds = [] as const;

export interface Comparison {
  readonly coverage: Coverage;
  readonly daily: ReadonlyArray<Daily>;
  readonly period: Record<string, unknown>;
  readonly totals: Totals;
}

export interface Coverage {
  readonly calendar_days: number;
  readonly declared_complete_days: number;
  readonly observed_receipt_days: number;
  readonly period_days: number;
  readonly status: "complete" | "partial" | "missing";
}

export interface Daily {
  readonly average_receipt: string | null;
  readonly date: string;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
  readonly state: "missing_calendar" | "incomplete" | "observed" | "no_eligible_receipts" | "comparison_unavailable";
}

export interface DatasetOption {
  readonly id: string;
  readonly label: string;
  readonly stores: ReadonlyArray<StoreOption>;
  readonly version: number;
}

export interface SalesContext {
  readonly datasets: ReadonlyArray<DatasetOption>;
  readonly default_period: Record<string, unknown>;
  readonly eligibility: Record<string, unknown>;
  readonly schema_version: "sales-report-context/v1";
  readonly workspace_id: string;
}

export interface SalesResponse {
  readonly changes: Record<string, unknown>;
  readonly comparability_status: "comparable" | "not_comparable";
  readonly comparison: Comparison | null;
  readonly coverage: Coverage;
  readonly daily: ReadonlyArray<Daily>;
  readonly lineage: Record<string, unknown>;
  readonly manifest: Record<string, unknown>;
  readonly mart: Record<string, unknown>;
  readonly metrics: ReadonlyArray<Record<string, unknown>>;
  readonly parameters: Record<string, unknown>;
  readonly policy_hash: string;
  readonly request_hash: string;
  readonly result_id: string;
  readonly schema_version: "sales-report/v1";
  readonly semantic_dataset_version_id: string;
  readonly totals: Totals;
  readonly trust: Record<string, unknown>;
}

export interface SalesRunRequest {
  readonly comparison?: "none" | "previous_year_same_dates";
  readonly ends_on?: string;
  readonly semantic_dataset_version_id: string;
  readonly starts_on?: string;
  readonly store_id?: string | null;
}

export interface StoreOption {
  readonly id: string;
  readonly label: string;
}

export interface Totals {
  readonly average_receipt: string | null;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
}
