// Generated by custometry-foundation-openapi-ts v1. Do not edit.
export const contractSourceDigest = "0c86583e3608f63d8773c6f3a99d121dea499da89a8c0e5b01bf153c2f150b86" as const;
export const externalJsonSchemaIds = [] as const;

export interface BusinessCalendarProfile {
  readonly fiscal_year_start_day?: 1;
  readonly fiscal_year_start_month?: number;
  readonly kind?: "month_based";
  readonly schema_version?: "business-calendar/v1";
  readonly timezone?: "UTC";
  readonly week_start?: "monday";
  readonly year_label?: "start_year" | "end_year";
}

export interface BusinessCalendarVersion {
  readonly content_hash: string;
  readonly created_at: string;
  readonly created_by: string | null;
  readonly previous_version_id: string | null;
  readonly profile: BusinessCalendarProfile;
  readonly version_id: string;
  readonly workspace_id: string;
}

export interface CalendarError {
  readonly code: "AUTHENTICATION_FAILED" | "FORBIDDEN" | "CSRF_FAILED" | "NOT_FOUND" | "CALENDAR_REVISION_CONFLICT" | "CALENDAR_IDEMPOTENCY_CONFLICT" | "STORAGE_UNAVAILABLE";
}

export interface HTTPValidationError {
  readonly detail?: ReadonlyArray<ValidationError>;
}

export interface UpdateCalendarRequest {
  readonly expected_revision: number;
  readonly idempotency_key: string;
  readonly profile: BusinessCalendarProfile;
}

export interface ValidationError {
  readonly loc: ReadonlyArray<string | number>;
  readonly msg: string;
  readonly type: string;
}

export interface WorkspaceCalendarDefault {
  readonly calendar: BusinessCalendarVersion;
  readonly revision: number;
  readonly workspace_id: string;
}

export class WorkspaceCalendarClient {
  public constructor(private readonly baseUrl: string, private readonly fetcher: typeof fetch = globalThis.fetch.bind(globalThis)) {}
  private async request<T>(path: string, input?: unknown, csrf?: string): Promise<T> {
    const response = await this.fetcher(`${this.baseUrl}${path}`, {
      method: input === undefined ? "GET" : "POST", credentials: "same-origin", cache: "no-store",
      headers: input === undefined ? {} : {"Content-Type": "application/json", "X-CSRF-Token": csrf ?? ""},
      ...(input === undefined ? {} : {body: JSON.stringify(input)}),
    });
    if (!response.ok) { const error = await response.json() as {code?: string}; throw new Error(error.code ?? `CALENDAR_HTTP_${response.status}`); }
    return response.json() as Promise<T>;
  }
  public get(): Promise<WorkspaceCalendarDefault> { return this.request("/workspace-calendar/v1"); }
  public version(id: string, hash: string): Promise<BusinessCalendarVersion> { return this.request(`/workspace-calendar/v1/versions/${encodeURIComponent(id)}?content_hash=${encodeURIComponent(hash)}`); }
  public update(input: UpdateCalendarRequest, csrf: string): Promise<WorkspaceCalendarDefault> { return this.request("/workspace-calendar/v1/versions", input, csrf); }
}
