// Generated by custometry-foundation-openapi-ts v1. Do not edit.
export const contractSourceDigest = "b3ed0f0130f308ebfe386609131850257bda0861423f1ea8941a40731f46ffda" as const;
export const externalJsonSchemaIds = [] as const;

export type AnalyticalDocumentComposition = AnalyticalDocumentCompositionV1 | AnalyticalDocumentCompositionV2;

export interface AnalyticalDocumentCompositionV1 {
  readonly access_policy_id: string;
  readonly analytical_document_id: string;
  readonly analytical_document_version_id: string;
  readonly blocks: ReadonlyArray<Block>;
  readonly brand_profile_version_id: string;
  readonly chapters: ReadonlyArray<Record<string, unknown>>;
  readonly composition_schema_version: 1;
  readonly default_page_id: string;
  readonly filter_scope_bindings: ReadonlyArray<Record<string, unknown>>;
  readonly navigation_mode: "tabs";
  readonly pages: ReadonlyArray<Page>;
  readonly profile: "workbook_report";
  readonly sections: ReadonlyArray<Section>;
  readonly source_owner_ref: Record<string, unknown>;
  readonly workspace_id: string;
}

export interface AnalyticalDocumentCompositionV2 {
  readonly access_policy_id: string;
  readonly analytical_document_id: string;
  readonly analytical_document_version_id: string;
  readonly bindings_by_card: ReadonlyArray<CardResultBinding>;
  readonly blocks: ReadonlyArray<Block>;
  readonly brand_profile_version_id: string;
  readonly chapters: ReadonlyArray<Record<string, unknown>>;
  readonly chart_payloads?: ReadonlyArray<WorkspaceChartSpecV2>;
  readonly chart_specs: ReadonlyArray<Reference>;
  readonly comparisons?: ReadonlyArray<CardComparisonV1>;
  readonly composition_schema_version: 2;
  readonly default_page_id: string;
  readonly definition: ConfiguredReportV2;
  readonly filter_scope_bindings: ReadonlyArray<WorkspaceFilterBinding>;
  readonly navigation_mode: "tabs";
  readonly pages: ReadonlyArray<Page>;
  readonly profile: "workbook_report";
  readonly sections: ReadonlyArray<WorkspaceSection>;
  readonly source_owner_ref: Record<string, unknown>;
  readonly workspace_id: string;
}

export interface AnalyticsResultListResponse {
  readonly results: ReadonlyArray<AnalyticsResultResponse>;
  readonly visible_count: number;
}

export interface AnalyticsResultResponse {
  readonly applied_comparison_mode: string;
  readonly calendar_version_id: string;
  readonly comparability_status: "comparable" | "partial" | "not_comparable";
  readonly comparison_coverage: Record<string, unknown> | null;
  readonly comparison_policy_hash: string;
  readonly current_coverage: Record<string, unknown>;
  readonly freshness: Record<string, unknown>;
  readonly limitation_codes: ReadonlyArray<string>;
  readonly lineage: Record<string, unknown>;
  readonly manifest: Record<string, unknown>;
  readonly metric_groups: ReadonlyArray<MetricGroupProjection>;
  readonly normalized_filter_expression_hash: string;
  readonly policy_hash: string;
  readonly quality: Record<string, unknown>;
  readonly request_hash: string;
  readonly resolved_comparison_period: Record<string, unknown> | null;
  readonly resolved_current_period: Record<string, unknown>;
  readonly result_id: string;
  readonly result_type: "sales" | "customer" | "rfm";
  readonly rfm_profiles: ReadonlyArray<Record<string, unknown>>;
  readonly semantic_dataset_version_id: string;
  readonly timezone: string;
}

export interface AnalyticsRunRequest {
  readonly comparison: TimeComparisonRequest;
  readonly filters?: ReadonlyArray<TypedFilterRequest>;
  readonly result_type: "sales" | "customer" | "rfm";
  readonly rfm_frequency_measure?: "receipt_count" | "purchase_day_count";
  readonly rfm_score_bins?: number;
  readonly rfm_segment_rule_set_version?: "rfm-retail-v1";
  readonly semantic_dataset_version_id: string;
}

export interface ArtifactRef {
  readonly artifact_id: string;
  readonly content_hash: string;
}

export interface BaseSnapshotRef {
  readonly manifest: ArtifactRef;
  readonly snapshot_id: string;
  readonly version_id: string;
}

export interface Block {
  readonly block_id: string;
  readonly block_type: "metric_group" | "chart" | "table" | "result_trust";
  readonly content_binding?: null;
  readonly order: number;
  readonly presentation: Record<string, unknown>;
  readonly section_id: string;
  readonly source_binding: Record<string, unknown>;
}

export interface BrandProfileObject {
  readonly kind: "brand_profile";
  readonly payload: SystemBrandProfileV1;
  readonly reference: Reference;
}

export interface CalendarRef {
  readonly content_hash: string;
  readonly version_id: string;
}

export interface Card {
  readonly card_id: string;
  readonly local_store_ids: ReadonlyArray<string> | null;
  readonly metric_ref: MetricRef;
  readonly population_binding?: null;
  readonly target_action_binding?: null;
}

export interface CardComparisonV1 {
  readonly buckets: ReadonlyArray<ComparisonBucket>;
  readonly comparability_status: "comparable" | "descriptive" | "unavailable";
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly left: ComparisonSide;
  readonly manifest: ArtifactRef;
  readonly mode: "temporal" | "pair";
  readonly right: ComparisonSide;
  readonly schema_version: "card-comparison/v1";
  readonly totals: ComparisonValues;
}

export interface CardResultBinding {
  readonly bucket_projection: "net_revenue" | "receipt_count" | "average_receipt";
  readonly card_id: string;
  readonly configuration_hash: string;
  readonly effective_context_hash: string;
  readonly format: NumberFormat;
  readonly metric_ref: MetricRef;
  readonly readiness: "ready" | "no_data" | "comparison_unavailable";
  readonly result: ResultRef;
  readonly unit: "EUR" | "receipt" | "EUR/receipt";
}

export interface ChartSeriesRef {
  readonly artifact: ArtifactRef;
  readonly axis: "left" | "right";
  readonly card_id: string;
  readonly field: "net_revenue" | "receipt_count" | "average_receipt" | "left" | "right" | "absolute_delta" | "relative_delta_percent";
  readonly unit: "EUR" | "receipt" | "EUR/receipt" | "percent";
}

export type ChartSpec = LineChartSpecV1 | WorkspaceChartSpecV2;

export interface ChartSpecObject {
  readonly kind: "chart_spec";
  readonly payload: LineChartSpecV1;
  readonly reference: Reference;
}

export interface CompanyPackObject {
  readonly kind: "company_pack";
  readonly payload: SystemCompanyPackV1;
  readonly reference: Reference;
}

export interface CompareRequest {
  readonly left: CardResultBinding;
  readonly right: CardResultBinding | null;
  readonly semantic_dataset_version_id: string;
}

export interface Comparison {
  readonly coverage: custometry_api__analytics__sales_models__Coverage;
  readonly daily: ReadonlyArray<Daily>;
  readonly period: Record<string, unknown>;
  readonly totals: Totals;
}

export interface ComparisonBucket {
  readonly absolute_delta: string | null;
  readonly bucket_id: string;
  readonly left: string | null;
  readonly left_coverage: packages__contracts__analytics__workspace__Coverage;
  readonly reason_codes: ReadonlyArray<string>;
  readonly relative_delta_percent: string | null;
  readonly right: string | null;
  readonly right_coverage: packages__contracts__analytics__workspace__Coverage;
}

export interface ComparisonSide {
  readonly baseline_dates: ReadonlyArray<string> | null;
  readonly card_id: string;
  readonly context: EffectiveContext;
  readonly format: NumberFormat;
  readonly metric_ref: MetricRef;
  readonly result: ResultRef;
  readonly unit: "EUR" | "receipt" | "EUR/receipt";
}

export interface ComparisonValues {
  readonly absolute_delta: string | null;
  readonly left: string | null;
  readonly left_coverage: packages__contracts__analytics__workspace__Coverage;
  readonly reason_codes: ReadonlyArray<string>;
  readonly relative_delta_percent: string | null;
  readonly right: string | null;
  readonly right_coverage: packages__contracts__analytics__workspace__Coverage;
}

export interface ConfiguredReportV2 {
  readonly base_snapshot_ref: BaseSnapshotRef;
  readonly brand_profile: Reference;
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly common_context: QueryContext;
  readonly company_pack: Reference;
  readonly creator_principal_id: string;
  readonly default_workset_id: string | null;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly report_id: string;
  readonly schema_version: "configured-report/v2";
  readonly selection: SingleSelection | PairSelection | null;
  readonly semantic_dataset_version_id: string;
  readonly title: string;
  readonly worksets: ReadonlyArray<Workset>;
}

export interface Coverage {
  readonly calendar_days: number;
  readonly declared_complete_days: number;
  readonly eligible_receipts: number;
  readonly expected_days: number;
  readonly observed_days: number;
  readonly reason_codes: ReadonlyArray<string>;
  readonly state: "complete" | "partial" | "unavailable";
}

export interface CreatorApplyRequest {
  readonly base_revision: number;
  readonly contract_version: "configured-report/v2";
  readonly definition: ConfiguredReportV2;
  readonly mode: "creator";
  readonly reuse_result_ids?: ReadonlyArray<string> | null;
}

export interface Daily {
  readonly average_receipt: string | null;
  readonly date: string;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
  readonly state: "missing_calendar" | "incomplete" | "observed" | "no_eligible_receipts" | "comparison_unavailable";
}

export interface DatasetOption {
  readonly id: string;
  readonly label: string;
  readonly stores: ReadonlyArray<StoreOption>;
  readonly version: number;
}

export interface DayAlignment {
  readonly baseline_date: string | null;
  readonly current_date: string;
}

export interface DraftResponse {
  readonly author_principal_id: string;
  readonly composition: AnalyticalDocumentCompositionV1;
  readonly contract_version: "draft-report/v1";
  readonly lifecycle: "owned_draft_preview";
  readonly manifest: Record<string, unknown>;
  readonly page_snapshot: Record<string, unknown>;
  readonly references: PreparedResponse;
  readonly report_id: string;
  readonly result: Record<string, unknown>;
  readonly revision: number;
  readonly saved_at: string;
  readonly snapshot: Record<string, unknown>;
  readonly snapshot_id: string;
  readonly title: string;
  readonly version_id: string;
}

export interface EffectiveContext {
  readonly alignment: "none" | "previous_year_same_dates";
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly ends_on: string;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly starts_on: string;
  readonly store_ids: ReadonlyArray<string>;
  readonly timezone?: "UTC";
  readonly week_start?: "monday";
}

export interface HTTPValidationError {
  readonly detail?: ReadonlyArray<ValidationError>;
}

export interface LineChartSpecV1 {
  readonly access_policy: Record<string, unknown>;
  readonly accessibility: Record<string, unknown>;
  readonly annotations: ReadonlyArray<Record<string, unknown>>;
  readonly axes: ReadonlyArray<Record<string, unknown>>;
  readonly chart_data: Record<string, unknown>;
  readonly chart_spec_id: string;
  readonly chart_type: "line";
  readonly created_at: string;
  readonly description_key: null;
  readonly dimensions: ReadonlyArray<Record<string, unknown>>;
  readonly export_policy: Record<string, unknown>;
  readonly interaction: Record<string, unknown>;
  readonly measures: ReadonlyArray<Record<string, unknown>>;
  readonly range_timeline: null;
  readonly schema_version: "1.0.0";
  readonly series: ReadonlyArray<Record<string, unknown>>;
  readonly source_binding: Record<string, unknown>;
  readonly title_key: string;
  readonly title_override: null;
  readonly visual_semantics: Record<string, unknown>;
  readonly workspace_id: string;
}

export interface LocalizedName {
  readonly en: string;
  readonly ru: string;
}

export interface MetricGroupProjection {
  readonly group_id: string;
  readonly group_order: number;
  readonly metrics: ReadonlyArray<MetricProjection>;
}

export interface MetricProjection {
  readonly absolute_change: string | null;
  readonly compact_comparison: string | null;
  readonly compact_current: string | null;
  readonly comparison_value: string | null;
  readonly current_value: string | null;
  readonly limitation_codes: ReadonlyArray<string>;
  readonly metric_id: string;
  readonly metric_order: number;
  readonly percent_change: string | null;
}

export interface MetricRef {
  readonly content_hash: string;
  readonly metric_id: "net_revenue" | "receipt_count" | "average_receipt";
  readonly version_id: string;
}

export interface MetricValues {
  readonly average_receipt: string | null;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
}

export interface NumberFormat {
  readonly decimal_places: number;
}

export interface Page {
  readonly chapter_id?: null;
  readonly layout_mode: "flow";
  readonly order: number;
  readonly page_id: string;
  readonly title: Record<string, unknown>;
  readonly visibility: "visible";
}

export interface PairSelection {
  readonly display: "series";
  readonly left_card_id: string;
  readonly mode: "pair";
  readonly right_card_id: string;
}

export interface PeriodRequest {
  readonly ends_on: string;
  readonly starts_on: string;
}

export interface PrepareRequest {
  readonly contract_version: "draft-report/v1";
  readonly result_id: string;
}

export interface PreparedResponse {
  readonly brand_profile: BrandProfileObject;
  readonly chart_spec: ChartSpecObject;
  readonly company_pack: CompanyPackObject;
  readonly contract_version: "draft-report/v1";
}

export interface QueryContext {
  readonly ends_on: string;
  readonly starts_on: string;
  readonly store_ids: ReadonlyArray<string> | null;
}

export interface ReaderApplyRequest {
  readonly base_revision: number;
  readonly contract_version: "configured-report/v2";
  readonly mode: "reader";
  readonly view_override: ReaderViewOverride;
}

export interface ReaderViewOverride {
  readonly display: ViewDisplay;
  readonly query_context: ViewQueryContext;
}

export interface Reference {
  readonly content_hash: string;
  readonly id: string;
}

export interface ReportCapabilities {
  readonly definition_edit: boolean;
  readonly exact_preview: boolean;
  readonly saved_view_save: boolean;
  readonly view_apply: boolean;
}

export interface ReportList {
  readonly reports: ReadonlyArray<ReportSummary>;
  readonly visible_count: number;
}

export interface ReportSummary {
  readonly lifecycle: "owned_draft_preview";
  readonly report_id: string;
  readonly revision: number;
  readonly saved_at: string;
  readonly snapshot_id: string;
  readonly title: string;
  readonly version_id: string;
}

export interface ResultRef {
  readonly manifest: ArtifactRef;
  readonly result_id: string;
  readonly schema_version: "metric-workspace/v2";
}

export interface SalesContext {
  readonly datasets: ReadonlyArray<DatasetOption>;
  readonly default_period: Record<string, unknown>;
  readonly eligibility: Record<string, unknown>;
  readonly schema_version: "sales-report-context/v1";
  readonly workspace_id: string;
}

export interface SalesResponse {
  readonly changes: Record<string, unknown>;
  readonly comparability_status: "comparable" | "not_comparable";
  readonly comparison: Comparison | null;
  readonly coverage: custometry_api__analytics__sales_models__Coverage;
  readonly daily: ReadonlyArray<Daily>;
  readonly lineage: Record<string, unknown>;
  readonly manifest: Record<string, unknown>;
  readonly mart: Record<string, unknown>;
  readonly metrics: ReadonlyArray<Record<string, unknown>>;
  readonly parameters: Record<string, unknown>;
  readonly policy_hash: string;
  readonly request_hash: string;
  readonly result_id: string;
  readonly schema_version: "sales-report/v1";
  readonly semantic_dataset_version_id: string;
  readonly totals: Totals;
  readonly trust: Record<string, unknown>;
}

export interface SalesRunRequest {
  readonly comparison?: "none" | "previous_year_same_dates";
  readonly ends_on?: string;
  readonly semantic_dataset_version_id: string;
  readonly starts_on?: string;
  readonly store_id?: string | null;
}

export interface SaveRequest {
  readonly brand_profile: Reference;
  readonly chart_spec: Reference;
  readonly company_pack: Reference;
  readonly contract_version: "draft-report/v1";
  readonly expected_revision: number;
  readonly idempotency_key: string;
  readonly result_id: string;
  readonly title: string;
}

export interface SaveViewRequest {
  readonly contract_version: "saved-view/v1";
  readonly document_version_id: string;
  readonly expected_revision: number;
  readonly idempotency_key: string;
  readonly result_ids: ReadonlyArray<string>;
  readonly view_override: ReaderViewOverride;
}

export interface SavedViewV1 {
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly display: ViewDisplay;
  readonly document_content_hash: string;
  readonly document_version_id: string;
  readonly owner_principal_id: string;
  readonly page_ids: ReadonlyArray<string>;
  readonly query_context: ViewQueryContext;
  readonly report_id: string;
  readonly result_scope: ReadonlyArray<CardResultBinding>;
  readonly revision: number;
  readonly saved_view_id: string;
  readonly schema_version: "saved-view/v1";
  readonly version_id: string;
  readonly workspace_id: string;
}

export interface Section {
  readonly order: number;
  readonly page_id: string;
  readonly parent_section_id?: null;
  readonly section_id: string;
  readonly title?: null;
}

export interface SingleSelection {
  readonly card_id: string;
  readonly display: "series" | "delta_trend";
  readonly mode: "single";
  readonly temporal: "none" | "previous_year_same_dates";
}

export interface StoreOption {
  readonly id: string;
  readonly label: string;
}

export interface SystemBrandProfileV1 {
  readonly brand_profile_version_id: string;
  readonly font_family: "Inter";
  readonly name: string;
  readonly remote_assets: ReadonlyArray<string>;
  readonly schema_version: "system-brand/v1";
  readonly source: Record<string, unknown>;
  readonly themes: ReadonlyArray<"abyss" | "graphite" | "frost" | "paper">;
  readonly token_version: string;
  readonly tokens: ReadonlyArray<Record<string, unknown>>;
}

export interface SystemCompanyPackV1 {
  readonly brand_profile: Reference;
  readonly company_pack_version_id: string;
  readonly localization_catalogs: ReadonlyArray<"en" | "ru">;
  readonly methodology_packs: ReadonlyArray<Record<string, unknown>>;
  readonly metric_versions: ReadonlyArray<Record<string, unknown>>;
  readonly name: string;
  readonly schema_version: "system-company-pack/v1";
}

export interface TemporalBucket {
  readonly baseline_dates: ReadonlyArray<string>;
  readonly bucket_id: string;
  readonly changes: Record<string, unknown>;
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly values: MetricValues;
}

export interface TemporalProjection {
  readonly alignment: "previous_year_same_dates";
  readonly baseline_dates: ReadonlyArray<string>;
  readonly buckets: ReadonlyArray<TemporalBucket>;
  readonly changes: Record<string, unknown>;
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly excluded_baseline_dates: ReadonlyArray<string>;
  readonly mapping: ReadonlyArray<DayAlignment>;
  readonly reason_codes: ReadonlyArray<string>;
  readonly totals: MetricValues;
}

export interface TimeComparisonRequest {
  readonly calendar_version_id: string;
  readonly comparison_period?: PeriodRequest | null;
  readonly current_period: PeriodRequest;
  readonly definition_compatibility_policy: "require_same_versions" | "allow_explicit_rebase";
  readonly incomplete_period_policy: "exclude" | "comparable_elapsed_days" | "explicit_partial";
  readonly iso_week_53_policy: "calendar_map" | "exclude" | "explicit_partial";
  readonly leap_day_policy: "calendar_map" | "exclude" | "merge_with_feb_28";
  readonly mode: "none" | "previous_year_same_dates" | "previous_year_calendar_aligned" | "previous_year_iso_week_aligned" | "previous_year_fiscal_period" | "previous_year_comparable_elapsed_days";
  readonly timezone: string;
}

export interface Totals {
  readonly average_receipt: string | null;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
}

export interface TypedFilterRequest {
  readonly field: "store_id" | "channel_id" | "currency" | "status" | "net_amount";
  readonly operator: "eq" | "in" | "gte" | "lte";
  readonly value: string | number | string | ReadonlyArray<string>;
}

export interface ValidationError {
  readonly loc: ReadonlyArray<string | number>;
  readonly msg: string;
  readonly type: string;
}

export type VersionedReport = DraftResponse | WorkspaceReportResponse;

export interface ViewDisplay {
  readonly active_workset_id: string | null;
  readonly card_order: ReadonlyArray<string>;
  readonly density: "comfortable" | "compact";
  readonly hidden_card_ids: ReadonlyArray<string>;
  readonly representation: "chart" | "table";
  readonly selection: SingleSelection | PairSelection | null;
}

export interface ViewQueryContext {
  readonly ends_on: string;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly starts_on: string;
  readonly store_ids: ReadonlyArray<string> | null;
}

export interface Workset {
  readonly cards: ReadonlyArray<Card>;
  readonly name: LocalizedName;
  readonly owner_principal_id: string;
  readonly visibility: "personal";
  readonly workset_id: string;
}

export type WorkspaceApplyRequest = CreatorApplyRequest | ReaderApplyRequest;

export interface WorkspaceApplyResponse {
  readonly access_fingerprint: string;
  readonly base_revision: number;
  readonly bindings_by_card: ReadonlyArray<CardResultBinding>;
  readonly chart_payloads?: ReadonlyArray<WorkspaceChartSpecV2>;
  readonly chart_specs: ReadonlyArray<Reference>;
  readonly comparison: CardComparisonV1 | null;
  readonly configuration_hash: string;
  readonly contract_version: "configured-report/v2";
  readonly definition: ConfiguredReportV2 | null;
  readonly status: "ready" | "no_data" | "comparison_unavailable";
  readonly view_context: ReaderViewOverride | null;
}

export interface WorkspaceApplyResult {
  readonly bindings: ReadonlyArray<CardResultBinding>;
  readonly results: ReadonlyArray<WorkspaceResultV2>;
  readonly schema_version?: "workspace-apply/v2";
}

export interface WorkspaceBucket {
  readonly bucket_end_exclusive: string;
  readonly bucket_id: string;
  readonly bucket_start: string;
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly clipped: boolean;
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly effective_end_exclusive: string;
  readonly effective_ends_on: string;
  readonly effective_start: string;
  readonly effective_starts_on: string;
  readonly fiscal_half: number | null;
  readonly fiscal_quarter: number | null;
  readonly fiscal_year: number | null;
  readonly is_partial_bucket: boolean;
  readonly label: string;
  readonly natural_ends_on: string;
  readonly natural_starts_on: string;
  readonly state: "ready" | "no_data" | "incomplete";
  readonly values: MetricValues;
}

export interface WorkspaceChartSpecV2 {
  readonly accessibility_table: ArtifactRef;
  readonly chart_spec_id: string;
  readonly chart_type: "line";
  readonly comparison: ArtifactRef | null;
  readonly schema_version: "2.0.0";
  readonly selection: SingleSelection | PairSelection;
  readonly series: ReadonlyArray<ChartSeriesRef>;
  readonly workspace_id: string;
}

export interface WorkspaceDay {
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly date: string;
  readonly values: MetricValues;
}

export interface WorkspaceEditorResponse {
  readonly base_definition: ConfiguredReportV2 | null;
  readonly capabilities: ReportCapabilities;
  readonly contract_version?: "workspace-editor/v2";
  readonly definition: ConfiguredReportV2 | null;
  readonly report: VersionedReport;
  readonly saved_view_revision: number;
}

export interface WorkspaceFilterBinding {
  readonly combine_mode: "intersect";
  readonly expression: QueryContext;
  readonly linked_target_block_ids: ReadonlyArray<string>;
  readonly owner_principal_id: string;
  readonly policy_hash: string;
  readonly precedence: ReadonlyArray<"security" | "system_locked" | "source_metric" | "document" | "card">;
  readonly scope: "document" | "workset" | "card";
  readonly scope_resource_id: string;
}

export interface WorkspaceLineage {
  readonly data_as_of: string;
  readonly metric_components: ReadonlyArray<MetricRef>;
  readonly source_artifacts: ReadonlyArray<ArtifactRef>;
  readonly source_calendar_version_id: string;
}

export interface WorkspaceReportResponse {
  readonly author_principal_id: string;
  readonly capabilities: ReportCapabilities;
  readonly composition: AnalyticalDocumentCompositionV2;
  readonly contract_version: "configured-report/v2";
  readonly manifest: ArtifactRef;
  readonly page_manifests: ReadonlyArray<ArtifactRef>;
  readonly report_id: string;
  readonly revision: number;
  readonly saved_at: string;
  readonly saved_view: Reference;
  readonly snapshot_id: string;
  readonly version_id: string;
}

export interface WorkspaceResultV2 {
  readonly buckets: ReadonlyArray<WorkspaceBucket>;
  readonly comparison: CardComparisonV1 | null;
  readonly coverage: packages__contracts__analytics__workspace__Coverage;
  readonly daily: ReadonlyArray<WorkspaceDay>;
  readonly effective_context: EffectiveContext;
  readonly lineage: WorkspaceLineage;
  readonly manifest: ArtifactRef;
  readonly metric_refs: ReadonlyArray<MetricRef>;
  readonly policy_hash: string;
  readonly publication_hash: string;
  readonly request_hash: string;
  readonly result_id: string;
  readonly schema_version: "metric-workspace/v2";
  readonly semantic_dataset_version_id: string;
  readonly temporal: TemporalProjection | null;
  readonly totals: MetricValues;
  readonly trust: WorkspaceTrust;
}

export interface WorkspaceRunRequest {
  readonly alignment: "none" | "previous_year_same_dates";
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly common: QueryContext;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly local_store_ids: ReadonlyArray<string> | null;
  readonly metric_refs: ReadonlyArray<MetricRef>;
  readonly semantic_dataset_version_id: string;
}

export interface WorkspaceSaveRequest {
  readonly chart_specs: ReadonlyArray<Reference>;
  readonly configuration_hash: string;
  readonly contract_version: "configured-report/v2";
  readonly definition: ConfiguredReportV2;
  readonly expected_revision: number;
  readonly expected_saved_view_revision: number;
  readonly idempotency_key: string;
  readonly result_ids: ReadonlyArray<string>;
}

export interface WorkspaceSection {
  readonly order: number;
  readonly page_id: string;
  readonly parent_section_id?: null;
  readonly section_id: string;
  readonly title: LocalizedName;
}

export interface WorkspaceTrust {
  readonly reason_codes: ReadonlyArray<string>;
  readonly status: "ready" | "no_data" | "comparison_unavailable";
}

export interface custometry_api__analytics__sales_models__Coverage {
  readonly calendar_days: number;
  readonly declared_complete_days: number;
  readonly observed_receipt_days: number;
  readonly period_days: number;
  readonly status: "complete" | "partial" | "missing";
}

export interface packages__contracts__analytics__workspace__Coverage {
  readonly calendar_days: number;
  readonly declared_complete_days: number;
  readonly eligible_receipts: number;
  readonly expected_days: number;
  readonly observed_days: number;
  readonly reason_codes: ReadonlyArray<string>;
  readonly state: "complete" | "partial" | "unavailable";
}


export class WorkspaceRequestError extends Error {
  public constructor(public readonly code: string, public readonly status: number, public readonly retryable: boolean) { super(code); this.name = "WorkspaceRequestError"; }
}
export class WorkspaceReportClient {
  public constructor(private readonly baseUrl: string, private readonly fetcher: typeof fetch = globalThis.fetch.bind(globalThis)) {}
  private async request<T>(path: string, body?: unknown, csrf?: string): Promise<T> {
    const response = await this.fetcher(`${this.baseUrl}/v2${path}`, {
      method: body === undefined ? "GET" : "POST", credentials: "same-origin", cache: "no-store",
      headers: body === undefined ? {} : {"Content-Type":"application/json","X-CSRF-Token":csrf ?? ""},
      ...(body === undefined ? {} : {body:JSON.stringify(body)}),
    });
    if (!response.ok) { const failure = await response.json() as {code?: string; retryable?: boolean}; throw new WorkspaceRequestError(failure.code ?? `WORKSPACE_HTTP_${response.status}`, response.status, failure.retryable === true); }
    return response.json() as Promise<T>;
  }
  public get(id: string): Promise<WorkspaceEditorResponse> { return this.request(`/${encodeURIComponent(id)}`); }
  public preview(id: string, snapshot: string): Promise<WorkspaceEditorResponse> { return this.request(`/${encodeURIComponent(id)}/snapshots/${encodeURIComponent(snapshot)}`); }
  public apply(id: string, body: WorkspaceApplyRequest, csrf: string): Promise<WorkspaceApplyResponse> { return this.request(`/${encodeURIComponent(id)}/apply`,body,csrf); }
  public save(id: string, body: WorkspaceSaveRequest, csrf: string): Promise<WorkspaceReportResponse> { return this.request(`/${encodeURIComponent(id)}/versions`,body,csrf); }
  public views(id: string): Promise<SavedViewV1[]> { return this.request(`/${encodeURIComponent(id)}/saved-views`); }
  public saveView(id: string, body: SaveViewRequest, csrf: string, view?: string): Promise<SavedViewV1> { return this.request(`/${encodeURIComponent(id)}/saved-views${view ? `/${encodeURIComponent(view)}/versions` : ""}`,body,csrf); }
}
