// Generated by custometry-foundation-openapi-ts v1. Do not edit.
export const contractSourceDigest = "d58ad483017c25cef246d7e20f82f17ed491aff525f2f5183d1f99b99386b017" as const;
export const externalJsonSchemaIds = [] as const;

export type AnalyticalDocumentComposition = AnalyticalDocumentCompositionV1 | AnalyticalDocumentCompositionV2;

export interface AnalyticalDocumentCompositionV1 {
  readonly access_policy_id: string;
  readonly analytical_document_id: string;
  readonly analytical_document_version_id: string;
  readonly blocks: ReadonlyArray<Block>;
  readonly brand_profile_version_id: string;
  readonly chapters: ReadonlyArray<Record<string, unknown>>;
  readonly composition_schema_version: 1;
  readonly default_page_id: string;
  readonly filter_scope_bindings: ReadonlyArray<Record<string, unknown>>;
  readonly navigation_mode: "tabs";
  readonly pages: ReadonlyArray<Page>;
  readonly profile: "workbook_report";
  readonly sections: ReadonlyArray<Section>;
  readonly source_owner_ref: Record<string, unknown>;
  readonly workspace_id: string;
}

export interface AnalyticalDocumentCompositionV2 {
  readonly access_policy_id: string;
  readonly analytical_document_id: string;
  readonly analytical_document_version_id: string;
  readonly bindings_by_card: ReadonlyArray<CardResultBinding>;
  readonly blocks: ReadonlyArray<Block>;
  readonly brand_profile_version_id: string;
  readonly chapters: ReadonlyArray<Record<string, unknown>>;
  readonly chart_specs: ReadonlyArray<Reference>;
  readonly composition_schema_version: 2;
  readonly default_page_id: string;
  readonly definition: ConfiguredReportV2;
  readonly filter_scope_bindings: ReadonlyArray<WorkspaceFilterBinding>;
  readonly navigation_mode: "tabs";
  readonly pages: ReadonlyArray<Page>;
  readonly profile: "workbook_report";
  readonly sections: ReadonlyArray<Section>;
  readonly source_owner_ref: Record<string, unknown>;
  readonly workspace_id: string;
}

export interface ArtifactRef {
  readonly artifact_id: string;
  readonly content_hash: string;
}

export interface BaseSnapshotRef {
  readonly manifest: ArtifactRef;
  readonly snapshot_id: string;
  readonly version_id: string;
}

export interface Block {
  readonly block_id: string;
  readonly block_type: "metric_group" | "chart" | "table" | "result_trust";
  readonly content_binding?: null;
  readonly order: number;
  readonly presentation: Record<string, unknown>;
  readonly section_id: string;
  readonly source_binding: Record<string, unknown>;
}

export interface BrandProfileObject {
  readonly kind: "brand_profile";
  readonly payload: SystemBrandProfileV1;
  readonly reference: Reference;
}

export interface CalendarRef {
  readonly content_hash: string;
  readonly version_id: string;
}

export interface Card {
  readonly card_id: string;
  readonly local_store_ids: ReadonlyArray<string> | null;
  readonly metric_ref: MetricRef;
  readonly population_binding?: null;
  readonly target_action_binding?: null;
}

export interface CardComparisonV1 {
  readonly buckets: ReadonlyArray<ComparisonBucket>;
  readonly comparability_status: "comparable" | "descriptive" | "unavailable";
  readonly coverage: Coverage;
  readonly left: ComparisonSide;
  readonly manifest: ArtifactRef;
  readonly mode: "temporal" | "pair";
  readonly right: ComparisonSide;
  readonly schema_version: "card-comparison/v1";
  readonly totals: ComparisonValues;
}

export interface CardResultBinding {
  readonly bucket_projection: "net_revenue" | "receipt_count" | "average_receipt";
  readonly card_id: string;
  readonly configuration_hash: string;
  readonly effective_context_hash: string;
  readonly format: NumberFormat;
  readonly metric_ref: MetricRef;
  readonly readiness: "ready" | "no_data" | "comparison_unavailable";
  readonly result: ResultRef;
  readonly unit: "EUR" | "receipt" | "EUR/receipt";
}

export interface ChartSeriesRef {
  readonly artifact: ArtifactRef;
  readonly axis: "left" | "right";
  readonly card_id: string;
  readonly field: "net_revenue" | "receipt_count" | "average_receipt" | "left" | "right" | "absolute_delta" | "relative_delta_percent";
  readonly unit: "EUR" | "receipt" | "EUR/receipt" | "percent";
}

export type ChartSpec = LineChartSpecV1 | WorkspaceChartSpecV2;

export interface ChartSpecObject {
  readonly kind: "chart_spec";
  readonly payload: LineChartSpecV1;
  readonly reference: Reference;
}

export interface CompanyPackObject {
  readonly kind: "company_pack";
  readonly payload: SystemCompanyPackV1;
  readonly reference: Reference;
}

export interface ComparisonBucket {
  readonly absolute_delta: string | null;
  readonly bucket_id: string;
  readonly left: string | null;
  readonly left_coverage: Coverage;
  readonly reason_codes: ReadonlyArray<string>;
  readonly relative_delta_percent: string | null;
  readonly right: string | null;
  readonly right_coverage: Coverage;
}

export interface ComparisonSide {
  readonly baseline_dates: ReadonlyArray<string> | null;
  readonly card_id: string;
  readonly context: EffectiveContext;
  readonly format: NumberFormat;
  readonly metric_ref: MetricRef;
  readonly result: ResultRef;
  readonly unit: "EUR" | "receipt" | "EUR/receipt";
}

export interface ComparisonValues {
  readonly absolute_delta: string | null;
  readonly left: string | null;
  readonly left_coverage: Coverage;
  readonly reason_codes: ReadonlyArray<string>;
  readonly relative_delta_percent: string | null;
  readonly right: string | null;
  readonly right_coverage: Coverage;
}

export interface ConfiguredReportV2 {
  readonly base_snapshot_ref: BaseSnapshotRef;
  readonly brand_profile: Reference;
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly common_context: QueryContext;
  readonly company_pack: Reference;
  readonly creator_principal_id: string;
  readonly default_workset_id: string | null;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly report_id: string;
  readonly schema_version: "configured-report/v2";
  readonly selection: SingleSelection | PairSelection | null;
  readonly semantic_dataset_version_id: string;
  readonly title: string;
  readonly worksets: ReadonlyArray<Workset>;
}

export interface Coverage {
  readonly calendar_days: number;
  readonly declared_complete_days: number;
  readonly eligible_receipts: number;
  readonly expected_days: number;
  readonly observed_days: number;
  readonly reason_codes: ReadonlyArray<string>;
  readonly state: "complete" | "partial" | "unavailable";
}

export interface CreatorApplyRequest {
  readonly base_revision: number;
  readonly contract_version: "configured-report/v2";
  readonly definition: ConfiguredReportV2;
  readonly mode: "creator";
}

export interface DayAlignment {
  readonly baseline_date: string | null;
  readonly current_date: string;
}

export interface DraftResponse {
  readonly author_principal_id: string;
  readonly composition: AnalyticalDocumentCompositionV1;
  readonly contract_version: "draft-report/v1";
  readonly lifecycle: "owned_draft_preview";
  readonly manifest: Record<string, unknown>;
  readonly page_snapshot: Record<string, unknown>;
  readonly references: PreparedResponse;
  readonly report_id: string;
  readonly result: Record<string, unknown>;
  readonly revision: number;
  readonly saved_at: string;
  readonly snapshot: Record<string, unknown>;
  readonly snapshot_id: string;
  readonly title: string;
  readonly version_id: string;
}

export interface EffectiveContext {
  readonly alignment: "none" | "previous_year_same_dates";
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly ends_on: string;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly starts_on: string;
  readonly store_ids: ReadonlyArray<string>;
  readonly timezone?: "UTC";
  readonly week_start?: "monday";
}

export interface LineChartSpecV1 {
  readonly access_policy: Record<string, unknown>;
  readonly accessibility: Record<string, unknown>;
  readonly annotations: ReadonlyArray<Record<string, unknown>>;
  readonly axes: ReadonlyArray<Record<string, unknown>>;
  readonly chart_data: Record<string, unknown>;
  readonly chart_spec_id: string;
  readonly chart_type: "line";
  readonly created_at: string;
  readonly description_key: null;
  readonly dimensions: ReadonlyArray<Record<string, unknown>>;
  readonly export_policy: Record<string, unknown>;
  readonly interaction: Record<string, unknown>;
  readonly measures: ReadonlyArray<Record<string, unknown>>;
  readonly range_timeline: null;
  readonly schema_version: "1.0.0";
  readonly series: ReadonlyArray<Record<string, unknown>>;
  readonly source_binding: Record<string, unknown>;
  readonly title_key: string;
  readonly title_override: null;
  readonly visual_semantics: Record<string, unknown>;
  readonly workspace_id: string;
}

export interface LocalizedName {
  readonly en: string;
  readonly ru: string;
}

export interface MetricRef {
  readonly content_hash: string;
  readonly metric_id: "net_revenue" | "receipt_count" | "average_receipt";
  readonly version_id: string;
}

export interface MetricValues {
  readonly average_receipt: string | null;
  readonly net_revenue: string | null;
  readonly receipt_count: string | null;
}

export interface NumberFormat {
  readonly decimal_places: number;
}

export interface Page {
  readonly chapter_id?: null;
  readonly layout_mode: "flow";
  readonly order: number;
  readonly page_id: string;
  readonly title: Record<string, unknown>;
  readonly visibility: "visible";
}

export interface PairSelection {
  readonly display: "series";
  readonly left_card_id: string;
  readonly mode: "pair";
  readonly right_card_id: string;
}

export interface PreparedResponse {
  readonly brand_profile: BrandProfileObject;
  readonly chart_spec: ChartSpecObject;
  readonly company_pack: CompanyPackObject;
  readonly contract_version: "draft-report/v1";
}

export interface QueryContext {
  readonly ends_on: string;
  readonly starts_on: string;
  readonly store_ids: ReadonlyArray<string> | null;
}

export interface ReaderApplyRequest {
  readonly base_revision: number;
  readonly contract_version: "configured-report/v2";
  readonly mode: "reader";
  readonly view_override: ReaderViewOverride;
}

export interface ReaderViewOverride {
  readonly display: ViewDisplay;
  readonly query_context: ViewQueryContext;
}

export interface Reference {
  readonly content_hash: string;
  readonly id: string;
}

export interface ReportCapabilities {
  readonly definition_edit: boolean;
  readonly exact_preview: boolean;
  readonly saved_view_save: boolean;
  readonly view_apply: boolean;
}

export interface ResultRef {
  readonly manifest: ArtifactRef;
  readonly result_id: string;
  readonly schema_version: "metric-workspace/v2";
}

export interface SaveViewRequest {
  readonly contract_version: "saved-view/v1";
  readonly document_version_id: string;
  readonly expected_revision: number;
  readonly idempotency_key: string;
  readonly result_ids: ReadonlyArray<string>;
  readonly view_override: ReaderViewOverride;
}

export interface SavedViewV1 {
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly display: ViewDisplay;
  readonly document_content_hash: string;
  readonly document_version_id: string;
  readonly owner_principal_id: string;
  readonly page_ids: ReadonlyArray<string>;
  readonly query_context: ViewQueryContext;
  readonly report_id: string;
  readonly result_scope: ReadonlyArray<CardResultBinding>;
  readonly revision: number;
  readonly saved_view_id: string;
  readonly schema_version: "saved-view/v1";
  readonly version_id: string;
  readonly workspace_id: string;
}

export interface Section {
  readonly order: number;
  readonly page_id: string;
  readonly parent_section_id?: null;
  readonly section_id: string;
  readonly title?: null;
}

export interface SingleSelection {
  readonly card_id: string;
  readonly display: "series" | "delta_trend";
  readonly mode: "single";
  readonly temporal: "none" | "previous_year_same_dates";
}

export interface SystemBrandProfileV1 {
  readonly brand_profile_version_id: string;
  readonly font_family: "Inter";
  readonly name: string;
  readonly remote_assets: ReadonlyArray<string>;
  readonly schema_version: "system-brand/v1";
  readonly source: Record<string, unknown>;
  readonly themes: ReadonlyArray<"abyss" | "graphite" | "frost" | "paper">;
  readonly token_version: string;
  readonly tokens: ReadonlyArray<Record<string, unknown>>;
}

export interface SystemCompanyPackV1 {
  readonly brand_profile: Reference;
  readonly company_pack_version_id: string;
  readonly localization_catalogs: ReadonlyArray<"en" | "ru">;
  readonly methodology_packs: ReadonlyArray<Record<string, unknown>>;
  readonly metric_versions: ReadonlyArray<Record<string, unknown>>;
  readonly name: string;
  readonly schema_version: "system-company-pack/v1";
}

export interface TemporalBucket {
  readonly baseline_dates: ReadonlyArray<string>;
  readonly bucket_id: string;
  readonly changes: Record<string, unknown>;
  readonly coverage: Coverage;
  readonly values: MetricValues;
}

export interface TemporalProjection {
  readonly alignment: "previous_year_same_dates";
  readonly baseline_dates: ReadonlyArray<string>;
  readonly buckets: ReadonlyArray<TemporalBucket>;
  readonly changes: Record<string, unknown>;
  readonly coverage: Coverage;
  readonly excluded_baseline_dates: ReadonlyArray<string>;
  readonly mapping: ReadonlyArray<DayAlignment>;
  readonly reason_codes: ReadonlyArray<string>;
  readonly totals: MetricValues;
}

export type VersionedReport = DraftResponse | WorkspaceReportResponse;

export interface ViewDisplay {
  readonly active_workset_id: string | null;
  readonly card_order: ReadonlyArray<string>;
  readonly density: "comfortable" | "compact";
  readonly hidden_card_ids: ReadonlyArray<string>;
  readonly representation: "chart" | "table";
  readonly selection: SingleSelection | PairSelection | null;
}

export interface ViewQueryContext {
  readonly ends_on: string;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly starts_on: string;
  readonly store_ids: ReadonlyArray<string> | null;
}

export interface Workset {
  readonly cards: ReadonlyArray<Card>;
  readonly name: LocalizedName;
  readonly owner_principal_id: string;
  readonly visibility: "personal";
  readonly workset_id: string;
}

export type WorkspaceApplyRequest = CreatorApplyRequest | ReaderApplyRequest;

export interface WorkspaceApplyResponse {
  readonly access_fingerprint: string;
  readonly base_revision: number;
  readonly bindings_by_card: ReadonlyArray<CardResultBinding>;
  readonly chart_specs: ReadonlyArray<Reference>;
  readonly comparison: CardComparisonV1 | null;
  readonly configuration_hash: string;
  readonly contract_version: "configured-report/v2";
  readonly definition: ConfiguredReportV2 | null;
  readonly status: "ready" | "no_data" | "comparison_unavailable";
  readonly view_context: ReaderViewOverride | null;
}

export interface WorkspaceApplyResult {
  readonly bindings: ReadonlyArray<CardResultBinding>;
  readonly results: ReadonlyArray<WorkspaceResultV2>;
  readonly schema_version?: "workspace-apply/v2";
}

export interface WorkspaceBucket {
  readonly bucket_end_exclusive: string;
  readonly bucket_id: string;
  readonly bucket_start: string;
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly clipped: boolean;
  readonly coverage: Coverage;
  readonly effective_end_exclusive: string;
  readonly effective_ends_on: string;
  readonly effective_start: string;
  readonly effective_starts_on: string;
  readonly fiscal_half: number | null;
  readonly fiscal_quarter: number | null;
  readonly fiscal_year: number | null;
  readonly is_partial_bucket: boolean;
  readonly label: string;
  readonly natural_ends_on: string;
  readonly natural_starts_on: string;
  readonly state: "ready" | "no_data" | "incomplete";
  readonly values: MetricValues;
}

export interface WorkspaceChartSpecV2 {
  readonly accessibility_table: ArtifactRef;
  readonly chart_spec_id: string;
  readonly chart_type: "line";
  readonly comparison: ArtifactRef | null;
  readonly schema_version: "2.0.0";
  readonly selection: SingleSelection | PairSelection;
  readonly series: ReadonlyArray<ChartSeriesRef>;
  readonly workspace_id: string;
}

export interface WorkspaceDay {
  readonly coverage: Coverage;
  readonly date: string;
  readonly values: MetricValues;
}

export interface WorkspaceFilterBinding {
  readonly combine_mode: "intersect";
  readonly expression: QueryContext;
  readonly linked_target_block_ids: ReadonlyArray<string>;
  readonly owner_principal_id: string;
  readonly policy_hash: string;
  readonly precedence: ReadonlyArray<"security" | "system_locked" | "source_metric" | "document" | "card">;
  readonly scope: "document" | "workset" | "card";
  readonly scope_resource_id: string;
}

export interface WorkspaceLineage {
  readonly data_as_of: string;
  readonly metric_components: ReadonlyArray<MetricRef>;
  readonly source_artifacts: ReadonlyArray<ArtifactRef>;
  readonly source_calendar_version_id: string;
}

export interface WorkspaceReportResponse {
  readonly author_principal_id: string;
  readonly capabilities: ReportCapabilities;
  readonly composition: AnalyticalDocumentCompositionV2;
  readonly contract_version: "configured-report/v2";
  readonly manifest: ArtifactRef;
  readonly page_manifests: ReadonlyArray<ArtifactRef>;
  readonly report_id: string;
  readonly revision: number;
  readonly saved_at: string;
  readonly saved_view: Reference;
  readonly snapshot_id: string;
  readonly version_id: string;
}

export interface WorkspaceResultV2 {
  readonly buckets: ReadonlyArray<WorkspaceBucket>;
  readonly comparison: CardComparisonV1 | null;
  readonly coverage: Coverage;
  readonly daily: ReadonlyArray<WorkspaceDay>;
  readonly effective_context: EffectiveContext;
  readonly lineage: WorkspaceLineage;
  readonly manifest: ArtifactRef;
  readonly metric_refs: ReadonlyArray<MetricRef>;
  readonly policy_hash: string;
  readonly publication_hash: string;
  readonly request_hash: string;
  readonly result_id: string;
  readonly schema_version: "metric-workspace/v2";
  readonly semantic_dataset_version_id: string;
  readonly temporal: TemporalProjection | null;
  readonly totals: MetricValues;
  readonly trust: WorkspaceTrust;
}

export interface WorkspaceRunRequest {
  readonly alignment: "none" | "previous_year_same_dates";
  readonly calendar_basis: "calendar" | "fiscal";
  readonly calendar_ref: CalendarRef;
  readonly common: QueryContext;
  readonly grain: "day" | "week" | "month" | "quarter" | "half_year" | "year";
  readonly local_store_ids: ReadonlyArray<string> | null;
  readonly metric_refs: ReadonlyArray<MetricRef>;
  readonly semantic_dataset_version_id: string;
}

export interface WorkspaceSaveRequest {
  readonly chart_specs: ReadonlyArray<Reference>;
  readonly configuration_hash: string;
  readonly contract_version: "configured-report/v2";
  readonly definition: ConfiguredReportV2;
  readonly expected_revision: number;
  readonly expected_saved_view_revision: number;
  readonly idempotency_key: string;
  readonly result_ids: ReadonlyArray<string>;
}

export interface WorkspaceTrust {
  readonly reason_codes: ReadonlyArray<string>;
  readonly status: "ready" | "no_data" | "comparison_unavailable";
}
