export type SalesLanguage = "en" | "ru";

const copy = {
  en: {
    eyebrow: "Analytics · governed result", title: "Sales Overview",
    description: "Revenue, orders and average order value from the latest policy-visible W16 result.",
    refresh: "Refresh", refreshing: "Refreshing", apply: "Apply governed view", applying: "Applying",
    filters: "Period, comparison and filters", currentStart: "Current period starts", currentEnd: "Current period ends",
    comparison: "Comparison", noComparison: "No comparison", calendarAligned: "Previous year · calendar aligned",
    comparisonStart: "Comparison starts", comparisonEnd: "Comparison ends", store: "Store", channel: "Channel",
    optional: "Optional exact ID", revenue: "Revenue", orders: "Orders", aov: "Average order value", margin: "Margin",
    vsLy: "vs comparison", unavailable: "Unavailable", marginUnavailable: "Margin is not exposed by the W16 sales projection.",
    trend: "Revenue trend", trendUnavailable: "W16 exposes governed period aggregates, not a time-series trend.",
    contribution: "Contribution", delta: "Revenue delta", discount: "Recorded discount", contributionUnavailable: "Product/store/channel contribution is not exposed by W16.",
    breakdowns: "Breakdowns", product: "Product", storeBreakdown: "Store", channelBreakdown: "Channel",
    breakdownUnavailable: "No governed breakdown projection is available at this boundary.", trust: "Result Trust",
    openTrust: "Open Result Trust", closeTrust: "Close Result Trust", result: "Result", immutable: "Immutable result",
    period: "Resolved period", comparisonPeriod: "Resolved comparison", comparability: "Comparability", coverage: "Coverage",
    quality: "Quality", freshness: "Freshness", lastEvent: "Latest event date", policy: "Policy hash", filterHash: "Filter hash",
    lineage: "Lineage", grain: "Fact scope", discountSemantics: "Discount semantics", pvm: "PVM semantics",
    totalOnly: "The projection exposes aggregate recorded discount only; component attribution, cap diagnostics and value-origin labels are unavailable.",
    pvmUnavailable: "PVM decomposition is not part of W16. No causal or decomposed contribution claim is made.",
    firstLoading: "Loading policy-visible sales result", loadingBody: "Authorization and governed analytics are checked before values render.",
    empty: "No visible sales result", emptyBody: "Run a governed sales analysis in an authorized workflow, then return here.",
    forbidden: "Sales Overview is unavailable", forbiddenBody: "Current workspace policy did not authorize this result. Hidden values and counts were discarded.",
    failed: "Sales result could not be loaded", failedBody: "The last request failed safely. Retry without changing the governed result.",
    retry: "Retry", degraded: "Result is degraded", stale: "Result freshness is stale", refreshFailed: "Refresh failed; the last authorized result remains visible.",
    readOnly: "Current policy grants analysis.read but not analysis.run. Period and filter controls remain read-only.",
    partial: "Partial", comparable: "Comparable", notComparable: "Not comparable", observedDays: "observed days",
    notClassified: "Not classified by W16", ready: "Ready", statusUpdate: "Sales result updated.",
    invalidPeriod: "Period start must not be after period end.", sourceBoundary: "Real W16 aggregate boundary",
  },
  ru: {
    eyebrow: "Аналитика · управляемый результат", title: "Обзор продаж",
    description: "Выручка, заказы и средний чек из последнего доступного по policy результата W16.",
    refresh: "Обновить", refreshing: "Обновляем", apply: "Применить управляемый срез", applying: "Применяем",
    filters: "Период, сравнение и фильтры", currentStart: "Начало текущего периода", currentEnd: "Конец текущего периода",
    comparison: "Сравнение", noComparison: "Без сравнения", calendarAligned: "Прошлый год · календарное выравнивание",
    comparisonStart: "Начало периода сравнения", comparisonEnd: "Конец периода сравнения", store: "Магазин", channel: "Канал",
    optional: "Необязательный точный ID", revenue: "Выручка", orders: "Заказы", aov: "Средний чек", margin: "Маржа",
    vsLy: "к сравнению", unavailable: "Недоступно", marginUnavailable: "Маржа не входит в sales-проекцию W16.",
    trend: "Тренд выручки", trendUnavailable: "W16 отдаёт управляемые агрегаты периодов, но не временной ряд.",
    contribution: "Вклад", delta: "Изменение выручки", discount: "Учтённая скидка", contributionUnavailable: "Вклад товара, магазина и канала не входит в W16.",
    breakdowns: "Разрезы", product: "Товар", storeBreakdown: "Магазин", channelBreakdown: "Канал",
    breakdownUnavailable: "На этой границе нет управляемой проекции разреза.", trust: "Доверие к результату",
    openTrust: "Открыть доверие к результату", closeTrust: "Закрыть доверие к результату", result: "Результат", immutable: "Неизменяемый результат",
    period: "Разрешённый период", comparisonPeriod: "Разрешённое сравнение", comparability: "Сопоставимость", coverage: "Покрытие",
    quality: "Качество", freshness: "Актуальность", lastEvent: "Последняя дата события", policy: "Хеш policy", filterHash: "Хеш фильтра",
    lineage: "Происхождение", grain: "Гранулярность факта", discountSemantics: "Семантика скидок", pvm: "Семантика PVM",
    totalOnly: "Проекция отдаёт только агрегированную учтённую скидку; component attribution, cap diagnostics и value-origin labels недоступны.",
    pvmUnavailable: "Декомпозиция PVM не входит в W16. Причинный или декомпозированный вклад не заявляется.",
    firstLoading: "Загружаем доступный по policy результат продаж", loadingBody: "До отображения значений проверяются authorization и управляемая аналитика.",
    empty: "Нет доступного результата продаж", emptyBody: "Запустите управляемый анализ продаж в разрешённом workflow и вернитесь сюда.",
    forbidden: "Обзор продаж недоступен", forbiddenBody: "Текущая policy workspace не разрешила результат. Скрытые значения и counts удалены.",
    failed: "Не удалось загрузить результат продаж", failedBody: "Последний запрос завершился безопасной ошибкой. Повторите без изменения результата.",
    retry: "Повторить", degraded: "Результат деградирован", stale: "Актуальность результата устарела", refreshFailed: "Обновление не удалось; последний разрешённый результат остаётся видимым.",
    readOnly: "Текущая policy даёт analysis.read, но не analysis.run. Период и фильтры доступны только для чтения.",
    partial: "Частично", comparable: "Сопоставимо", notComparable: "Несопоставимо", observedDays: "дней с данными",
    notClassified: "Не классифицировано W16", ready: "Готово", statusUpdate: "Результат продаж обновлён.",
    invalidPeriod: "Начало периода не может быть позже конца.", sourceBoundary: "Реальная агрегатная граница W16",
  },
} as const;

export function salesCopy(language: SalesLanguage): (typeof copy)[SalesLanguage] {
  return copy[language];
}
