FROM python:3.12.14-bookworm@sha256:581429e3df12d76e6af4be5ab7d0e7fc2013eb57dc23d2de691411c8efdbb970 AS build
ENV SOURCE_DATE_EPOCH=315532800 CFLAGS=-g0 CXXFLAGS=-g0
RUN pip install --no-cache-dir cmake==3.31.10 ninja==1.11.1.4 Cython==3.1.2 numpy==2.2.6 setuptools==80.9.0 setuptools_scm==8.3.1 wheel==0.45.1 packaging==25.0
COPY arrow-20-source.tar.gz /tmp/source.tar.gz
RUN echo '2d645173a55fd98e1f31764f6fbe0cbcaf64a62fefdca7548549f9bdea28654c  /tmp/source.tar.gz' | sha256sum -c - && mkdir /src && tar -xzf /tmp/source.tar.gz --strip-components=1 -C /src
RUN cmake -S /src/cpp -B /build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/arrow -DCMAKE_INSTALL_LIBDIR=lib -DARROW_BUILD_STATIC=OFF -DARROW_BUILD_SHARED=ON -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_ACERO=ON -DARROW_COMPUTE=ON -DARROW_DATASET=ON -DARROW_FILESYSTEM=ON -DARROW_IPC=ON -DARROW_PARQUET=ON -DARROW_CSV=ON -DARROW_JSON=ON -DARROW_WITH_BROTLI=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_ZSTD=ON -DARROW_FLIGHT=OFF -DARROW_S3=OFF -DARROW_GCS=OFF -DARROW_AZURE=OFF -DARROW_GANDIVA=OFF -DPARQUET_REQUIRE_ENCRYPTION=OFF -DARROW_JEMALLOC=OFF -DARROW_MIMALLOC=OFF -DARROW_BUILD_TESTS=OFF -DARROW_BUILD_EXAMPLES=OFF -DARROW_BUILD_BENCHMARKS=OFF
RUN cmake --build /build --parallel 2 && cmake --install /build
WORKDIR /src/python
ENV ARROW_HOME=/opt/arrow CMAKE_PREFIX_PATH=/opt/arrow LD_LIBRARY_PATH=/opt/arrow/lib PYARROW_BUNDLE_ARROW_CPP=1 PYARROW_BUILD_TYPE=release PYARROW_PARALLEL=2 SETUPTOOLS_SCM_PRETEND_VERSION=20.0.0
RUN python setup.py bdist_wheel && mkdir /out && cp dist/*.whl /out/ && cp /build/CMakeCache.txt /out/
FROM scratch AS output
COPY --from=build /out/ /
