import {workspaceCopy,metricNames,workspaceReason,workspaceUnit} from './workspace-copy';
import {useEffect,useRef,useState} from 'react';
import {useMutation,useQuery} from '@tanstack/react-query';
import {useNavigate,useLocation} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import type {configuredReports as W} from '@custometry/contracts';
import {PilotDocument} from './PilotDocument';
import {accessStore,csrf,reportQueries,type Actor} from './report-api';
import {workspaceReports,workspaceCalendar,workspaceContext,workspaceResults,queryIdentity,move,copyWorkset,orderedResultIds,viewDefinition} from './workspace-api';
import {WorkspacePlot,WorkspaceTable} from './WorkspaceProjection';
import {CalendarSettings} from './WorkspaceCalendar';
const names=metricNames;
type WorkspaceDraft={definition:W.ConfiguredReportV2;baseRevision:number;savedViewRevision:number};
const drafts=new Map<string,WorkspaceDraft>();accessStore.subscribe(()=>drafts.clear());
export function ConfiguredWorkspace({workspace,actor,preview}:{workspace:string;actor:Actor;preview:boolean}){
 const {i18n}=useTranslation();const locale=i18n.resolvedLanguage==='ru'?'ru':'en';const c=workspaceCopy[locale];
 const location=useLocation();const navigate=useNavigate();const id=location.pathname.split('/')[4];const snapshot=preview?location.pathname.split('/')[6]:undefined;
 const editor=useQuery({queryKey:['workspace-editor',workspace,id,snapshot],queryFn:()=>snapshot?workspaceReports.preview(id,snapshot):workspaceReports.get(id),refetchOnWindowFocus:false,refetchOnReconnect:false});
 const [definition,setDefinition]=useState<W.ConfiguredReportV2|null>(drafts.get(workspace+id)?.definition??null);
 const [baseRevision,setBaseRevision]=useState<number|null>(drafts.get(workspace+id)?.baseRevision??null);const [savedViewRevision,setSavedViewRevision]=useState<number|null>(drafts.get(workspace+id)?.savedViewRevision??null);
 const [dirty,setDirty]=useState(drafts.has(workspace+id));const [applied,setApplied]=useState<{response:W.WorkspaceApplyResponse;definition:W.ConfiguredReportV2}|null>(null);
 const [inspector,setInspector]=useState<'set'|'card'|'chart'|'context'|null>('set');const inspectorTrigger=useRef<HTMLElement|null>(null);const inspectorTitle=useRef<HTMLHeadingElement>(null);const openInspector=(panel:'set'|'card'|'chart'|'context',trigger?:HTMLElement)=>{inspectorTrigger.current=trigger??null;setInspector(panel);};const closeInspector=()=>{setInspector(null);inspectorTrigger.current?.focus();};
 useEffect(()=>{if(inspector)inspectorTitle.current?.focus();},[inspector]);
 const [search,setSearch]=useState('');const [active,setActive]=useState<string|null>(null);const [table,setTable]=useState(false);const [focus,setFocus]=useState(new URLSearchParams(location.search).get('focus')==='workspace');const focusButton=useRef<HTMLButtonElement>(null);const focusSurface=useRef<HTMLDivElement>(null);
 const [selected,setSelected]=useState<string[]>([]);const [bulk,setBulk]=useState<string[]|null>(null);const [bulkPreview,setBulkPreview]=useState(false);
 const [view,setView]=useState<W.SavedViewV1|null>(null);const [conflict,setConflict]=useState(false);const [notice,setNotice]=useState('');
 const latest=useRef({definition,dirty,baseRevision,savedViewRevision});latest.current={definition,dirty,baseRevision,savedViewRevision};
 useEffect(()=>{if(editor.data&&baseRevision===null){setBaseRevision(editor.data.report.revision);setSavedViewRevision(editor.data.saved_view_revision);}},[editor.data,baseRevision]);
 useEffect(()=>()=>{if(latest.current.dirty&&latest.current.definition&&!accessStore.get())drafts.set(workspace+id,{definition:latest.current.definition,baseRevision:latest.current.baseRevision??0,savedViewRevision:latest.current.savedViewRevision??0});else drafts.delete(workspace+id);},[workspace,id]);
 useEffect(()=>{if(!definition&&editor.data){const d=editor.data.definition??editor.data.base_definition;setDefinition(d);setActive(d?.default_workset_id??null);}},[definition,editor.data]);
 const d=definition;const editable=Boolean(editor.data?.capabilities.definition_edit)&&!preview;
 const context=useQuery({queryKey:['workspace-context',workspace,d?.semantic_dataset_version_id],queryFn:()=>workspaceContext(d!.semantic_dataset_version_id),enabled:Boolean(d)});
 const calendar=useQuery({queryKey:['workspace-calendar',workspace],queryFn:()=>workspaceCalendar.get(),enabled:Boolean(d)});
 const views=useQuery({queryKey:['workspace-views',workspace,id],queryFn:()=>workspaceReports.views(id),enabled:Boolean(d)&&!editable&&!preview});
 const legacy=editor.data?.report.contract_version==='draft-report/v1'?editor.data.report.result as unknown as W.SalesResponse:undefined;
 const stored=editor.data?.report.contract_version==='configured-report/v2'?editor.data.report.composition:undefined;
 const bindings=applied?.response.bindings_by_card??view?.result_scope??stored?.bindings_by_card??[];
 const resultQuery=useQuery({queryKey:['workspace-results',workspace,bindings.map(b=>[b.result.result_id,b.result.manifest.content_hash])],queryFn:()=>workspaceResults(d!.semantic_dataset_version_id,bindings),enabled:Boolean(d)&&bindings.length>0});
 const results=resultQuery.data??new Map<string,W.WorkspaceResultV2>();
 const comparison=applied?.response.comparison??(view?null:stored?.comparisons?.[0])??null;
 const baseDefinition=editor.data?.definition??editor.data?.base_definition;
 const savedDefinition=view&&baseDefinition?viewDefinition(baseDefinition,view):stored?.definition;
 const verifiedDefinition=applied?.definition??savedDefinition;
 const update=(patch:Partial<W.ConfiguredReportV2>)=>{setDefinition(previous=>previous?{...previous,...patch}:previous);setDirty(true);setNotice('');};
 const queryChanged=Boolean(d&&(!verifiedDefinition||queryIdentity(d)!==queryIdentity(verifiedDefinition)));
 const readerOverride=(value:W.ConfiguredReportV2):W.ReaderViewOverride=>({query_context:{...value.common_context,grain:value.grain},display:{active_workset_id:active??value.default_workset_id,card_order:value.worksets.flatMap(s=>s.cards.map(c=>c.card_id)),hidden_card_ids:[],representation:table?'table':'chart',density:'comfortable',selection:value.selection}});
 const applying=useMutation({mutationFn:async(value:W.ConfiguredReportV2)=>{const reuse=applied&&queryIdentity(value)===queryIdentity(applied.definition)?orderedResultIds(value,applied.response.bindings_by_card):stored&&queryIdentity(value)===queryIdentity(stored.definition)?orderedResultIds(value,stored.bindings_by_card):null;const response=await workspaceReports.apply(id,editable?{contract_version:'configured-report/v2',mode:'creator',base_revision:baseRevision??editor.data!.report.revision,definition:value,reuse_result_ids:reuse}:{contract_version:'configured-report/v2',mode:'reader',base_revision:baseRevision??editor.data!.report.revision,view_override:readerOverride(value)},csrf());return {response,definition:value};},onSuccess:value=>{setApplied(value);setNotice(c.calculationAppliedSaveSeparately);},onError:()=>setNotice(c.applyFailedYourDraftIsRetained)});
 const saving=useMutation({onMutate:()=>setNotice(''),mutationFn:async()=>{if(!d)throw Error('NO_DEFINITION');let prepared=applied?.response;const previous=verifiedDefinition;if(!previous||queryIdentity(d)!==queryIdentity(previous))throw Error('APPLY_REQUIRED');if(editable&&(!applied||JSON.stringify(d)!==JSON.stringify(applied.definition))){prepared=await workspaceReports.apply(id,{contract_version:'configured-report/v2',mode:'creator',base_revision:baseRevision??editor.data!.report.revision,definition:d,reuse_result_ids:orderedResultIds(d,bindings)},csrf());}if(editable){if(!prepared)throw Error('APPLY_REQUIRED');return workspaceReports.save(id,{contract_version:'configured-report/v2',definition:d,expected_revision:baseRevision??editor.data!.report.revision,expected_saved_view_revision:savedViewRevision??editor.data!.saved_view_revision,idempotency_key:crypto.randomUUID(),configuration_hash:prepared.configuration_hash,result_ids:prepared.bindings_by_card.map(b=>b.result.result_id),chart_specs:prepared.chart_specs},csrf());}const saved=await workspaceReports.saveView(id,{contract_version:'saved-view/v1',document_version_id:view?.document_version_id??editor.data!.report.version_id,expected_revision:view?.revision??0,idempotency_key:crypto.randomUUID(),result_ids:orderedResultIds(d,bindings),view_override:readerOverride(d)},csrf(),view?.saved_view_id);setView(saved);return saved;},onSuccess:async()=>{setDirty(false);drafts.delete(workspace+id);setConflict(false);const fresh=await editor.refetch();if(fresh.data){setBaseRevision(fresh.data.report.revision);setSavedViewRevision(fresh.data.saved_view_revision);}if(!editable)await views.refetch();setNotice(c.saved);},onError:error=>{setConflict(/CONFLICT/.test(error.message));setNotice(c.saveFailedYourChangesRemainIn);}});
 useEffect(()=>{const previous=applied?.definition??stored?.definition;if(d&&previous&&!queryChanged&&!applying.isPending&&!saving.isPending&&!applying.isError&&JSON.stringify(d.selection)!==JSON.stringify(previous.selection)&&editable)applying.mutate(d);},[d?.selection,queryChanged,applied,stored,editable]);
 const reload=async()=>{const response=await editor.refetch();if(response.data){setBaseRevision(response.data.report.revision);setSavedViewRevision(response.data.saved_view_revision);setDefinition(response.data.definition??response.data.base_definition);setApplied(null);setView(null);setDirty(false);setConflict(false);setNotice('');drafts.delete(workspace+id);saving.reset();applying.reset();}};
 useEffect(()=>{if(!dirty)return;const handler=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 useEffect(()=>{const changed=()=>setFocus(new URLSearchParams(window.location.search).get('focus')==='workspace');window.addEventListener('popstate',changed);return()=>window.removeEventListener('popstate',changed);},[]);
 useEffect(()=>{if(focus)focusSurface.current?.focus();else focusButton.current?.focus();},[focus]);
 if(editor.isError)return <div role="alert">{c.editorUnavailableCheckAccessAndServer}<button onClick={()=>void editor.refetch()}>{c.retry}</button><a href={location.pathname+'?legacy=1'}>{locale==='ru'?'Открыть прежний предпросмотр':'Open legacy preview'}</a></div>;
 if(!d)return <p role="status">{c.loadingReport}</p>;
 const current=d.worksets.find(s=>s.workset_id===(active??d.default_workset_id))??d.worksets[0];
 const busy=applying.isPending||saving.isPending;
 const alterSet=(set:W.Workset)=>update({worksets:d.worksets.map(s=>s.workset_id===set.workset_id?set:s)});
 const changeCards=(cards:readonly W.Card[])=>{if(!current)return;const ids=new Set(cards.map(c=>c.card_id));setSelected(previous=>previous.filter(id=>ids.has(id)));const selection=d.selection;alterSet({...current,cards});if(selection&&(selection.mode==='single'?!ids.has(selection.card_id):!ids.has(selection.left_card_id)||!ids.has(selection.right_card_id)))update({selection:null});};
 const newSet=()=>{const set:W.Workset={workset_id:crypto.randomUUID(),owner_principal_id:actor.principal_id,visibility:'personal',name:{ru:'Новый набор',en:'New workset'},cards:[]};update({worksets:[...d.worksets,set],default_workset_id:set.workset_id,selection:null});setActive(set.workset_id);setSelected([]);};
 const select=(card:W.Card)=>update({default_workset_id:current?.workset_id??d.default_workset_id,selection:{mode:'single',card_id:card.card_id,temporal:d.selection?.mode==='single'?d.selection.temporal:'none',display:d.selection?.mode==='single'?d.selection.display:'series'}});
 const closeFocus=()=>{setFocus(false);const url=new URL(window.location.href);url.searchParams.delete('focus');window.history.replaceState(null,'',url);};
 const stores=context.data?.stores??[];
 const storePicker=(label:string,value:readonly string[]|null,onChange:(v:string[]|null)=>void,disabled=false)=><fieldset disabled={disabled||busy}><legend>{label}</legend><label><input type="checkbox" checked={value===null} onChange={e=>onChange(e.target.checked?null:[])}/>{c.inheritAllPermitted}</label><div className="mw-stores">{stores.map(s=><label key={s.id}><input type="checkbox" disabled={value===null} checked={value?.includes(s.id)??false} onChange={e=>onChange(e.target.checked?[...(value??[]),s.id]:(value??[]).filter(id=>id!==s.id))}/>{s.label}</label>)}</div><small>{value?.length===0?c.emptyScopeNoDataSelected:''}</small></fieldset>;
 const displayed={...(verifiedDefinition??d),selection:queryChanged?(verifiedDefinition??d).selection:d.selection};
 const plot=<><WorkspacePlot definition={displayed} bindings={bindings} results={results} comparison={comparison} locale={locale} legacy={bindings.length?undefined:legacy}/><WorkspaceTable definition={displayed} bindings={bindings} results={results} comparison={comparison} locale={locale} legacy={bindings.length?undefined:legacy}/></>;
 return <PilotDocument model={{workspace:true,workspaceChrome:{period:d.common_context.starts_on+' — '+d.common_context.ends_on,comparison:d.selection?.mode==='single'&&d.selection.temporal!=='none'?c.sameDatesLastYear:d.selection?.mode==='pair'?c.compareTwoCards:c.none,stores:d.common_context.store_ids===null?c.inheritAllPermitted:d.common_context.store_ids.map(id=>stores.find(s=>s.id===id)?.label??id).join(', ')||c.empty,grain:d.grain,unavailable:c.goalsUnavailable},locale,title:d.title,source:'',start:d.common_context.starts_on,end:d.common_context.ends_on,store:'',comparison:'none',actor,status:busy?c.working:dirty?c.unsaved:c.saved,hint:'',busy,preview,focus:false,unapplied:queryChanged,conflict,stores}} actions={{inspector:openInspector,library:()=>{if(!dirty||confirm(c.discardUnsavedChanges))navigate(`/w/${workspace}/reports`);},title:title=>update({title}),locale:next=>{void i18n.changeLanguage(next);},draft:()=>{},apply:()=>applying.mutate(d),save:()=>saving.mutate(),reload:()=>void reload(),preview:()=>navigate(`/w/${workspace}/reports/${id}/snapshots/${editor.data!.report.snapshot_id}`),urlChanged:()=>{}}}>
  <div className="mw" data-inspector={inspector?"open":"closed"} aria-busy={busy}>
   <header className="mw-toolbar"><label>{c.reportTitle}<input value={d.title} maxLength={200} disabled={!editable||busy} onChange={e=>update({title:e.target.value})}/></label><button disabled={busy||preview||!editor.data?.capabilities.view_apply} onClick={()=>applying.mutate(d)}>{c.apply}</button><button disabled={busy||preview||conflict||queryChanged||(!editable&&!editor.data?.capabilities.saved_view_save)} onClick={()=>saving.mutate()}>{editable?c.saveReport:c.savePersonalView}</button><button onClick={()=>void reload()}>{c.reloadSaved}</button><button disabled={!editor.data?.capabilities.exact_preview} onClick={()=>navigate(`/w/${workspace}/reports/${id}/snapshots/${editor.data!.report.snapshot_id}`)}>{c.exactSnapshot}</button></header>
   <p role={applying.error||saving.error||resultQuery.error?'alert':'status'}>{notice}{resultQuery.error?c.resultsCouldNotBeVerified:''}{conflict?c.versionConflictExplicitlyReloadTheSaved:''}</p>
   {dirty&&<p>{c.showingTheLastAppliedResultContext}</p>}
   <div className="mw-toolbar"><h2>{c.metricsAndTrends}</h2><button onClick={e=>openInspector('context',e.currentTarget)}>{d.common_context.starts_on} — {d.common_context.ends_on} · {c.reportContext}</button><button onClick={e=>openInspector('set',e.currentTarget)}>{c.configureWorkset}</button></div>
   <div className="mw-toolbar" role="group" aria-label={c.worksets}>{d.worksets.map((set,index)=><div key={set.workset_id}><button aria-pressed={current?.workset_id===set.workset_id} onClick={()=>{setActive(set.workset_id);setSelected([]);update({default_workset_id:set.workset_id,selection:set.cards[0]?{mode:'single',card_id:set.cards[0].card_id,temporal:d.selection?.mode==='single'?d.selection.temporal:'none',display:'series'}:null});}}>{set.name[locale]}</button>{editable&&<><button aria-label={c.moveWorksetUp} disabled={busy||index===0} onClick={()=>update({worksets:move(d.worksets,index,-1)})}>↑</button><button aria-label={c.moveWorksetDown} disabled={busy||index===d.worksets.length-1} onClick={()=>update({worksets:move(d.worksets,index,1)})}>↓</button></>}</div>)}{editable&&<button disabled={busy||d.worksets.length>=20} onClick={newSet}>{c.addWorkset}</button>}</div>
   {current&&<>
   <div className="kpi-strip mw-cards">{current.cards.map((card)=>{const binding=bindings.find(b=>b.card_id===card.card_id);const result=binding?results.get(binding.result.result_id):undefined;const legacyValue=!binding&&legacy&&card.card_id===editor.data?.base_definition?.worksets.flatMap(s=>s.cards).find(c=>c.metric_ref.metric_id===card.metric_ref.metric_id)?.card_id?legacy.totals[card.metric_ref.metric_id]:!binding&&legacy&&card.card_id===(editor.data?.definition??editor.data?.base_definition)?.worksets.flatMap(s=>s.cards).find(c=>c.metric_ref.metric_id===card.metric_ref.metric_id)?.card_id?legacy.totals[card.metric_ref.metric_id]:null;const value=result?.totals[card.metric_ref.metric_id]??legacyValue;return <article className="kpi-card" key={card.card_id}><button aria-pressed={d.selection?.mode==='single'&&d.selection.card_id===card.card_id} onClick={()=>select(card)}>{names[locale][card.metric_ref.metric_id]}</button><strong className="kpi-value">{value==null?'—':new Intl.NumberFormat(locale,{maximumFractionDigits:binding?.format.decimal_places??(card.metric_ref.metric_id==='receipt_count'?0:2)}).format(Number(value))}</strong><small>{workspaceUnit(locale,binding?.unit??'')} · {binding?workspaceReason(locale,binding.readiness):c.notApplied}</small><label><input type="checkbox" checked={selected.includes(card.card_id)} onChange={e=>setSelected(e.target.checked?[...selected,card.card_id]:selected.filter(id=>id!==card.card_id))}/>{c.select}</label><button aria-label={c.configureCard} onClick={e=>{select(card);openInspector('card',e.currentTarget);}}>⚙</button><small>{result?result.effective_context.store_ids.length===stores.length?c.inheritAllPermitted:result.effective_context.store_ids.map(id=>stores.find(s=>s.id===id)?.label??id).join(', '):''}</small></article>;})}</div>
   </>}
   {!current&&<p>{c.noWorksetsYetAnEmptyReport}</p>}
   <div className="mw-toolbar"><button onClick={e=>openInspector('chart',e.currentTarget)}>{c.chartComparisonSettings}</button><button aria-pressed={!table} onClick={()=>setTable(false)}>{c.chart}</button><button aria-pressed={table} onClick={()=>setTable(true)}>{c.table}</button><button ref={focusButton} onClick={()=>{setFocus(true);const url=new URL(window.location.href);url.searchParams.set('focus','workspace');window.history.replaceState(null,'',url);}}>Focus</button><button disabled>{c.goalsUnavailable}</button><button disabled>{c.sharedWorksetUnavailable}</button></div>
   <section className="panel">{table?<WorkspaceTable definition={displayed} bindings={bindings} results={results} comparison={comparison} locale={locale} legacy={bindings.length?undefined:legacy}/>:<WorkspacePlot definition={displayed} bindings={bindings} results={results} comparison={comparison} locale={locale} legacy={bindings.length?undefined:legacy}/>}</section>
   {focus&&<div className="mw-focus" role="dialog" aria-modal="true" aria-label="Focus" ref={focusSurface} tabIndex={-1} onKeyDown={e=>{if(e.key==='Escape')closeFocus();if(e.key==='Tab'){const nodes=[...e.currentTarget.querySelectorAll<HTMLElement>('button,[tabindex="0"]')];if(e.shiftKey&&(e.target===nodes[0]||e.target===e.currentTarget)){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&e.target===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}}}><button onClick={closeFocus}>{c.closeFocus}</button>{plot}</div>}
   <details><summary>Result Trust</summary><p>{c.serverValuesCompletedEurReceiptsOnly}</p>{[...results.values()].map(r=><div key={r.result_id}><p>{workspaceReason(locale,r.trust.status)} · {workspaceReason(locale,r.coverage.state)} · {r.trust.reason_codes.map(code=>workspaceReason(locale,code)).join(', ')} · {r.coverage.reason_codes.map(code=>workspaceReason(locale,code)).join(', ')}</p><p>{r.lineage.data_as_of}</p><code>{r.result_id} · {r.manifest.content_hash}</code></div>)}</details>
   {!editable&&views.data&&<label>{c.mySavedViews}<select value={view?.saved_view_id??''} onChange={e=>{const v=views.data.find(v=>v.saved_view_id===e.target.value);if(baseDefinition){setView(v??null);setDefinition(v?viewDefinition(baseDefinition,v):baseDefinition);setTable(v?.display.representation==='table');setActive(v?.display.active_workset_id??baseDefinition.default_workset_id);setApplied(null);setDirty(false);setNotice('');}}}><option value="">{c.baseView}</option>{views.data.map(v=><option key={v.saved_view_id} value={v.saved_view_id}>{v.revision} · {v.version_id}</option>)}</select></label>}
   <p>{c.pinnedCalendar}: <code>{d.calendar_ref.version_id}</code></p><p>{c.currentCompanyCalendar}: <code>{calendar.data?.calendar.version_id??'—'}</code></p>
   {editable&&calendar.data&&<button disabled={busy||d.calendar_ref.version_id===calendar.data.calendar.version_id} onClick={()=>update({calendar_ref:{version_id:calendar.data!.calendar.version_id,content_hash:calendar.data!.calendar.content_hash},calendar_basis:'fiscal'})}>{c.adoptCompanyCalendar}</button>}
   <CalendarSettings actor={actor} locale={locale} value={calendar.data} onSaved={()=>void calendar.refetch()}/>
   {inspector&&<aside className="mw-inspector" aria-label={c.reportInspector} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();closeInspector();}if(e.key==='Tab'&&window.innerWidth<=1100){const nodes=[...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),summary')].filter(n=>n.getClientRects().length);if(e.shiftKey&&(e.target===nodes[0]||e.target===inspectorTitle.current)){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&e.target===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}}}>
    <header className="mw-toolbar"><h2 ref={inspectorTitle} tabIndex={-1}>{c.reportInspector}</h2><button aria-label={c.closeInspector} onClick={closeInspector}>×</button></header>
    <nav className="mw-toolbar" aria-label={c.inspectorSections}>{(['set','card','chart','context'] as const).map((panel,i)=><button key={panel} aria-pressed={inspector===panel} onClick={()=>setInspector(panel)}>{locale==='ru'?['Набор','Карточка','График','Контекст'][i]:['Set','Card','Chart','Context'][i]}</button>)}</nav>
    <div className="mw-inspector-body">
    {inspector==='context'&&<details open><summary>{c.reportContext}</summary><div className="mw-toolbar"><label>{c.from}<input type="date" disabled={preview||busy} value={d.common_context.starts_on} onChange={e=>update({common_context:{...d.common_context,starts_on:e.target.value}})}/></label><label>{c.to}<input type="date" disabled={preview||busy} value={d.common_context.ends_on} onChange={e=>update({common_context:{...d.common_context,ends_on:e.target.value}})}/></label><label>{c.grain}<select disabled={preview||busy} value={d.grain} onChange={e=>update({grain:e.target.value as W.ConfiguredReportV2['grain']})}>{['day','week','month','quarter','half_year','year'].map((v,i)=><option key={v} value={v}>{locale==='ru'?['День','Неделя','Месяц','Квартал','Полугодие','Год'][i]:['Day','Week','Month','Quarter','Half year','Year'][i]}</option>)}</select></label><label>{c.calendarBasis}<select disabled={!editable||busy} value={d.calendar_basis} onChange={e=>update({calendar_basis:e.target.value as 'calendar'|'fiscal'})}><option value="calendar">{c.calendar}</option><option value="fiscal">{c.fiscal}</option></select></label></div>{storePicker(c.commonStores,d.common_context.store_ids,value=>update({common_context:{...d.common_context,store_ids:value}}),preview)}</details>}
    {inspector==='set'&&current&&<><div className="mw-toolbar"><label>{c.worksetName}<input disabled={!editable||busy} value={current.name[locale]} maxLength={200} onChange={e=>alterSet({...current,name:{...current.name,[locale]:e.target.value}})}/></label>{editable&&<><button disabled={busy||d.worksets.length>=20||d.worksets.reduce((n,s)=>n+s.cards.length,0)+current.cards.length>200} onClick={()=>{const next=copyWorkset(current);update({worksets:[...d.worksets,next],default_workset_id:next.workset_id,selection:next.cards[0]?{mode:'single',card_id:next.cards[0].card_id,temporal:d.selection?.mode==='single'?d.selection.temporal:'none',display:'series'}:null});setActive(next.workset_id);setSelected([]);}}>{c.copyWorkset}</button><button disabled={busy} onClick={()=>{const sets=d.worksets.filter(s=>s!==current);update({worksets:sets,default_workset_id:sets[0]?.workset_id??null,selection:null});setActive(sets[0]?.workset_id??null);setSelected([]);}}>{c.removeWorkset}</button><button disabled={busy} onClick={()=>update({default_workset_id:current.workset_id})}>{c.defaultWorkset}</button></>}</div>    {editable&&<details><summary>{c.metricCatalog}</summary><label>{c.searchMetrics}<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{context.data?.metrics.filter(m=>names[locale][m.metric_id].toLowerCase().includes(search.toLowerCase())).map(metric=><button key={metric.metric_id} disabled={busy||current.cards.length>=50||d.worksets.reduce((n,s)=>n+s.cards.length,0)>=200} onClick={()=>changeCards([...current.cards,{card_id:crypto.randomUUID(),metric_ref:{metric_id:metric.metric_id,version_id:metric.version_id,content_hash:metric.content_hash},local_store_ids:null}])}>{names[locale][metric.metric_id]}</button>)}</details>}
   {editable&&selected.length>0&&<details><summary>{c.bulkStoreSettings}</summary>{storePicker(c.restriction,bulk,value=>{setBulk(value);setBulkPreview(false);})}<button onClick={()=>setBulkPreview(true)}>{c.previewApplicability}</button>{bulkPreview&&<><p>{c.cardsToChange} {selected.length}. {c.effectiveStores} {(bulk??stores.map(s=>s.id)).filter(id=>d.common_context.store_ids===null||d.common_context.store_ids.includes(id)).join(', ')||c.empty}</p><button onClick={()=>{changeCards(current.cards.map(c=>selected.includes(c.card_id)?{...c,local_store_ids:bulk}:c));setBulkPreview(false);}}>{c.applyToSelected}</button></>}</details>}

     <ol>{current.cards.map((card,index)=><li key={card.card_id}><span>{names[locale][card.metric_ref.metric_id]}</span><button aria-label={c.moveCardUp} disabled={!editable||busy||index===0} onClick={()=>changeCards(move(current.cards,index,-1))}>↑</button><button aria-label={c.moveCardDown} disabled={!editable||busy||index===current.cards.length-1} onClick={()=>changeCards(move(current.cards,index,1))}>↓</button><button disabled={!editable||busy} onClick={()=>changeCards(current.cards.filter(c=>c!==card))}>{c.remove}</button></li>)}</ol>
    </>}
    {inspector==='card'&&current&&(()=>{const card=current.cards.find(c=>d.selection?.mode==='single'&&c.card_id===d.selection.card_id)??current.cards[0];if(!card)return <p>{c.selectACard}</p>;const index=current.cards.indexOf(card);return <><h3>{names[locale][card.metric_ref.metric_id]}</h3>{editable&&<><div className="mw-toolbar"><button disabled={busy||index===0} aria-label={c.moveCardUp} onClick={()=>changeCards(move(current.cards,index,-1))}>↑</button><button disabled={busy||index===current.cards.length-1} aria-label={c.moveCardDown} onClick={()=>changeCards(move(current.cards,index,1))}>↓</button><button disabled={busy||current.cards.length>=50||d.worksets.reduce((n,s)=>n+s.cards.length,0)>=200} onClick={()=>changeCards([...current.cards,{...card,card_id:crypto.randomUUID()}])}>{c.copy}</button><button disabled={busy} onClick={()=>changeCards(current.cards.filter(c=>c!==card))}>{c.remove}</button></div><details><summary>{c.cardContext}</summary>{storePicker(c.localStores,card.local_store_ids,value=>changeCards(current.cards.map(c=>c===card?{...c,local_store_ids:value}:c)))}</details></>}</>;})()}
    {inspector==='chart'&&   <div className="mw-toolbar"><button disabled={selected.length!==2||preview} onClick={()=>update({default_workset_id:current?.workset_id??d.default_workset_id,selection:{mode:'pair',left_card_id:selected[0],right_card_id:selected[1],display:'series'}})}>{c.compareTwoCards}</button>{d.selection?.mode==='single'&&<><label>{c.comparison}<select disabled={preview} value={d.selection.temporal} onChange={e=>{if(d.selection?.mode==='single')update({selection:{...d.selection,temporal:e.target.value as 'none'|'previous_year_same_dates'}});}}><option value="none">{c.none}</option><option value="previous_year_same_dates">{c.sameDatesLastYear}</option></select></label><label>{c.display}<select value={d.selection.display} onChange={e=>{if(d.selection?.mode==='single')update({selection:{...d.selection,display:e.target.value as 'series'|'delta_trend'}});}}><option value="series">{c.series}</option><option value="delta_trend">{c.deltaTrend}</option></select></label></>}</div>}
    </div><footer><button disabled={busy||preview||!editor.data?.capabilities.view_apply} onClick={()=>applying.mutate(d)}>{c.apply}</button></footer>
   </aside>}

  </div>
 </PilotDocument>;
}
