// Product copy for the configured report surfaces.
export const workspaceCopy = {
  "ru": {
    "calculationAppliedSaveSeparately": "Расчёт применён. Сохранение выполняется отдельно.",
    "applyFailedYourDraftIsRetained": "Не удалось применить. Черновик сохранён в этой сессии.",
    "saved": "Сохранено",
    "saveFailedYourChangesRemainIn": "Сохранение не выполнено. Изменения остаются в черновике.",
    "editorUnavailableCheckAccessAndServer": "Редактор недоступен. Проверьте доступ и поддержку версии сервера.",
    "retry": "Повторить",
    "loadingReport": "Загрузка отчёта",
    "inheritAllPermitted": "Наследовать / все доступные",
    "emptyScopeNoDataSelected": "Пустая область: данные не выбраны",
    "working": "Выполняется",
    "unsaved": "Не сохранено",
    "discardUnsavedChanges": "Отменить несохранённые изменения?",
    "reportTitle": "Название отчёта",
    "apply": "Применить",
    "saveReport": "Сохранить отчёт",
    "savePersonalView": "Сохранить личный вид",
    "reloadSaved": "Загрузить сохранённый",
    "exactSnapshot": "Точный снимок",
    "resultsCouldNotBeVerified": " Не удалось проверить результаты.",
    "versionConflictExplicitlyReloadTheSaved": " Конфликт версий: загрузите сохранённую версию явно.",
    "showingTheLastAppliedResultContext": "Показан последний применённый результат. Изменения контекста требуют «Применить».",
    "metricsAndTrends": "Метрики и динамика",
    "reportContext": "Контекст отчёта",
    "configureWorkset": "Настроить набор",
    "worksets": "Наборы",
    "moveWorksetUp": "Набор выше",
    "moveWorksetDown": "Набор ниже",
    "addWorkset": "Добавить набор",
    "notApplied": "Не применено",
    "select": "Выбрать",
    "configureCard": "Настроить карточку",
    "noWorksetsYetAnEmptyReport": "Наборов пока нет. Пустой отчёт можно сохранить.",
    "chartComparisonSettings": "Настроить график / сравнение",
    "chart": "График",
    "table": "Таблица",
    "workspace": "focus",
    "goalsUnavailable": "Цели · недоступно",
    "sharedWorksetUnavailable": "Общий набор · недоступно",
    "closeFocus": "Закрыть Focus",
    "serverValuesCompletedEurReceiptsOnly": "Значения сервера. Только завершённые чеки EUR; ограничения связей товаров и покупателей сохраняются.",
    "mySavedViews": "Мои сохранённые виды",
    "baseView": "Базовый вид",
    "pinnedCalendar": "Закреплённый календарь",
    "currentCompanyCalendar": "Текущий календарь компании",
    "adoptCompanyCalendar": "Принять календарь компании",
    "reportInspector": "Инспектор отчёта",
    "closeInspector": "Закрыть инспектор",
    "inspectorSections": "Разделы инспектора",
    "from": "С",
    "to": "По",
    "grain": "Детализация",
    "calendarBasis": "Основа периодов",
    "calendar": "Календарная",
    "fiscal": "Финансовая",
    "commonStores": "Общие магазины",
    "worksetName": "Имя набора",
    "copyWorkset": "Копировать набор",
    "removeWorkset": "Удалить набор",
    "defaultWorkset": "Набор по умолчанию",
    "metricCatalog": "Каталог метрик",
    "searchMetrics": "Поиск метрики",
    "bulkStoreSettings": "Массовая настройка магазинов",
    "restriction": "Ограничение",
    "previewApplicability": "Предпросмотр применимости",
    "cardsToChange": "Будет изменено карточек:",
    "effectiveStores": "Эффективные магазины:",
    "empty": "Пусто",
    "applyToSelected": "Применить к выбранным",
    "moveCardUp": "Карточка выше",
    "moveCardDown": "Карточка ниже",
    "remove": "Удалить",
    "selectACard": "Выберите карточку",
    "copy": "Копия",
    "cardContext": "Контекст карточки",
    "localStores": "Локальные магазины",
    "compareTwoCards": "Сравнить две карточки",
    "comparison": "Сравнение",
    "none": "Нет",
    "sameDatesLastYear": "Те же даты год назад",
    "display": "Показать",
    "series": "Ряды",
    "deltaTrend": "Изменение",
    "companySettingsFinancialYear": "Настройки компании · финансовый год",
    "startsOnTheFirstDayOf": "Начало — первое число месяца. UTC, недели с понедельника. Календари 4-4-5 не поддерживаются.",
    "fiscalCalendar": "Финансовый календарь",
    "startMonth": "Месяц начала",
    "yearNaming": "Название года",
    "startYear": "По году начала",
    "endYear": "По году окончания",
    "savedReportsKeepTheirPinnedCalendar": "Сохранённые отчёты сохраняют свой календарь.",
    "saveCompanyCalendar": "Сохранить календарь компании",
    "aWorkspaceAdministratorCanChangeThese": "Изменять настройки может администратор workspace.",
    "couldNotSaveReloadSettingsAfter": "Не удалось сохранить. При конфликте обновите настройки.",
    "reloadSettings": "Обновить настройки",
    "calendarSaved": "Календарь сохранён"
  },
  "en": {
    "calculationAppliedSaveSeparately": "Calculation applied. Save separately.",
    "applyFailedYourDraftIsRetained": "Apply failed. Your draft is retained in this session.",
    "saved": "Saved",
    "saveFailedYourChangesRemainIn": "Save failed. Your changes remain in the draft.",
    "editorUnavailableCheckAccessAndServer": "Editor unavailable. Check access and server version support.",
    "retry": "Retry",
    "loadingReport": "Loading report",
    "inheritAllPermitted": "Inherit / all permitted",
    "emptyScopeNoDataSelected": "Empty scope: no data selected",
    "working": "Working",
    "unsaved": "Unsaved",
    "discardUnsavedChanges": "Discard unsaved changes?",
    "reportTitle": "Report title",
    "apply": "Apply",
    "saveReport": "Save report",
    "savePersonalView": "Save personal view",
    "reloadSaved": "Reload saved",
    "exactSnapshot": "Exact snapshot",
    "resultsCouldNotBeVerified": " Results could not be verified.",
    "versionConflictExplicitlyReloadTheSaved": " Version conflict: explicitly reload the saved version.",
    "showingTheLastAppliedResultContext": "Showing the last applied result. Context changes require Apply.",
    "metricsAndTrends": "Metrics and trends",
    "reportContext": "Report context",
    "configureWorkset": "Configure workset",
    "worksets": "Worksets",
    "moveWorksetUp": "Move workset up",
    "moveWorksetDown": "Move workset down",
    "addWorkset": "Add workset",
    "notApplied": "Not applied",
    "select": "Select",
    "configureCard": "Configure card",
    "noWorksetsYetAnEmptyReport": "No worksets yet. An empty report can be saved.",
    "chartComparisonSettings": "Chart / comparison settings",
    "chart": "Chart",
    "table": "Table",
    "workspace": "workspace",
    "goalsUnavailable": "Goals · unavailable",
    "sharedWorksetUnavailable": "Shared workset · unavailable",
    "closeFocus": "Close Focus",
    "serverValuesCompletedEurReceiptsOnly": "Server values. Completed EUR receipts only; product and customer relationship limitations remain.",
    "mySavedViews": "My saved views",
    "baseView": "Base view",
    "pinnedCalendar": "Pinned calendar",
    "currentCompanyCalendar": "Current company calendar",
    "adoptCompanyCalendar": "Adopt company calendar",
    "reportInspector": "Report inspector",
    "closeInspector": "Close inspector",
    "inspectorSections": "Inspector sections",
    "from": "From",
    "to": "To",
    "grain": "Grain",
    "calendarBasis": "Calendar basis",
    "calendar": "Calendar",
    "fiscal": "Fiscal",
    "commonStores": "Common stores",
    "worksetName": "Workset name",
    "copyWorkset": "Copy workset",
    "removeWorkset": "Remove workset",
    "defaultWorkset": "Default workset",
    "metricCatalog": "Metric catalog",
    "searchMetrics": "Search metrics",
    "bulkStoreSettings": "Bulk store settings",
    "restriction": "Restriction",
    "previewApplicability": "Preview applicability",
    "cardsToChange": "Cards to change:",
    "effectiveStores": "Effective stores:",
    "empty": "Empty",
    "applyToSelected": "Apply to selected",
    "moveCardUp": "Move card up",
    "moveCardDown": "Move card down",
    "remove": "Remove",
    "selectACard": "Select a card",
    "copy": "Copy",
    "cardContext": "Card context",
    "localStores": "Local stores",
    "compareTwoCards": "Compare two cards",
    "comparison": "Comparison",
    "none": "None",
    "sameDatesLastYear": "Same dates last year",
    "display": "Display",
    "series": "Series",
    "deltaTrend": "Delta trend",
    "companySettingsFinancialYear": "Company settings · financial year",
    "startsOnTheFirstDayOf": "Starts on the first day of a month. UTC, Monday weeks. 4-4-5 calendars are not supported.",
    "fiscalCalendar": "Fiscal calendar",
    "startMonth": "Start month",
    "yearNaming": "Year naming",
    "startYear": "Start year",
    "endYear": "End year",
    "savedReportsKeepTheirPinnedCalendar": "Saved reports keep their pinned calendar.",
    "saveCompanyCalendar": "Save company calendar",
    "aWorkspaceAdministratorCanChangeThese": "A workspace administrator can change these settings.",
    "couldNotSaveReloadSettingsAfter": "Could not save. Reload settings after a conflict.",
    "reloadSettings": "Reload settings",
    "calendarSaved": "Calendar saved"
  }
} as const;
export const metricNames={ru:{net_revenue:'Выручка',receipt_count:'Чеки',average_receipt:'Средний чек'},en:{net_revenue:'Net revenue',receipt_count:'Receipts',average_receipt:'Average receipt'}} as const;
const reasons:Record<string,readonly [string,string]>={ready:['Готово','Ready'],no_data:['Нет данных','No data'],comparison_unavailable:['Сравнение недоступно','Comparison unavailable'],complete:['Полный период','Complete'],partial:['Неполный период','Partial'],unavailable:['Недоступно','Unavailable'],incomplete:['Неполные данные','Incomplete'],EMPTY_EFFECTIVE_SCOPE:['Пустое пересечение магазинов','Empty store intersection'],NO_ELIGIBLE_RECEIPTS:['Нет подходящих чеков','No eligible receipts'],ZERO_BASELINE:['База равна нулю: процент недоступен','Zero baseline: percentage unavailable'],BASELINE_UNAVAILABLE:['Нет данных для базы сравнения','Baseline unavailable'],CURRENT_UNAVAILABLE:['Нет текущих данных','Current values unavailable'],CALENDAR_MISSING:['Нет календарного покрытия','Calendar coverage missing'],CALENDAR_INCOMPLETE:['Неполное календарное покрытие','Incomplete calendar coverage'],COVERAGE_INCOMPLETE:['Неполное покрытие','Incomplete coverage'],LEAP_DAY_SAME_DATE_UNAVAILABLE:['Нет той же даты для 29 февраля','No same-date mapping for February 29'],BASELINE_UNMAPPED_LEAP_DAY_EXCLUDED:['Лишний день високосного года исключён','Unmapped leap day excluded'],COMPLETED_EUR_ONLY:['Только завершённые чеки EUR','Completed EUR receipts only'],NOT_REFUND_ADJUSTED:['Без корректировки возвратов','Not adjusted for refunds'],CURRENT_ONLY_DIMENSIONS:['Измерения текущего периода','Current-period dimensions only'],PRODUCT_BASKET_COVERAGE_DEGRADED:['Ограниченное покрытие товарных связей','Limited product relationship coverage'],DIFFERENT_UNITS:['Разные единицы: разность не определяется','Different units: subtraction unavailable'],UNIT_MISMATCH:['Разные единицы измерения','Different measurement units']};
export function workspaceReason(locale:'ru'|'en',code:string):string{return reasons[code]?.[locale==='ru'?0:1]??`${locale==='ru'?'Ограничение':'Limitation'} (${code})`;}
export function workspaceUnit(locale:'ru'|'en',unit:string):string{return unit==='percent'?'%':unit==='receipt'?(locale==='ru'?'чеки':'receipts'):unit==='EUR/receipt'?(locale==='ru'?'EUR/чек':'EUR/receipt'):unit;}
