import {metricNames,workspaceReason,workspaceUnit} from './workspace-copy';
import {useEffect,useRef} from 'react';
import * as echarts from 'echarts/core';
import {LineChart} from 'echarts/charts';
import {GridComponent,TooltipComponent,LegendComponent,AriaComponent} from 'echarts/components';
import {SVGRenderer} from 'echarts/renderers';
import type {configuredReports as W} from '@custometry/contracts';
echarts.use([LineChart,GridComponent,TooltipComponent,LegendComponent,AriaComponent,SVGRenderer]);
interface Props {legacy?:W.SalesResponse;definition:W.ConfiguredReportV2;bindings:readonly W.CardResultBinding[];results:ReadonlyMap<string,W.WorkspaceResultV2>;comparison:W.CardComparisonV1|null;locale:'ru'|'en'}
export function projection({definition,bindings,results,comparison:provided,legacy}:Props){
 const selection=definition.selection;const ids=selection?.mode==='pair'?[selection.left_card_id,selection.right_card_id]:selection?[selection.card_id]:[];
 const comparison=provided&&provided.left.card_id===ids[0]&&(selection?.mode==='pair'?provided.right.card_id===ids[1]:selection?.mode==='single'&&selection.temporal!=='none')?provided:null;
 const selected=ids.map(id=>bindings.find(b=>b.card_id===id)).filter((b):b is W.CardResultBinding=>Boolean(b));
 if(selected.length===0&&legacy){const cards=ids.map(id=>definition.worksets.flatMap(s=>s.cards).find(c=>c.card_id===id)).filter((c):c is W.Card=>Boolean(c));const temporal=selection?.mode==='single'&&selection.temporal!=='none'&&legacy.comparison;const units=cards.map(c=>c.metric_ref.metric_id==='receipt_count'?'receipt':c.metric_ref.metric_id==='average_receipt'?'EUR/receipt':'EUR');if(temporal)units.push(units[0]);return {units,names:cards.map(c=>c.metric_ref.metric_id),rows:legacy.daily.map(b=>({id:b.date,label:b.date,dates:b.date,state:b.state,partial:false,values:[...cards.map(c=>b[c.metric_ref.metric_id]),...(temporal?[legacy.comparison?.daily.find(p=>p.date.slice(5)===b.date.slice(5))?.[cards[0].metric_ref.metric_id]??null]:[])],absolute:null,relative:null,reasons:[]}))};}
 const first=selected[0]?results.get(selected[0].result.result_id):undefined;
 const buckets=first?.buckets??[];
 const temporal=selection?.mode==='single'&&selection.temporal!=='none'?first?.temporal:null;
 const delta=selection?.mode==='single'&&selection.display==='delta_trend';
 const rows=buckets.map(b=>{const c=comparison?.buckets.find(c=>c.bucket_id===b.bucket_id)??(selected[0]?temporal?.buckets.find(t=>t.bucket_id===b.bucket_id)?.changes[selected[0].bucket_projection] as W.ComparisonValues|undefined:undefined);return {id:b.bucket_id,label:b.label,dates:`${b.effective_starts_on} — ${b.effective_ends_on}`,state:b.state,partial:b.is_partial_bucket,values:(comparison||temporal)?(delta?[c?.relative_delta_percent??null]:[c?.left??null,c?.right??null]):selected.map(binding=>results.get(binding.result.result_id)?.buckets.find(x=>x.bucket_id===b.bucket_id)?.values[binding.bucket_projection]??null),absolute:c?.absolute_delta??null,relative:c?.relative_delta_percent??null,reasons:c?.reason_codes??b.coverage.reason_codes};});
 const names=selected.map(b=>b.bucket_projection);
 const units=comparison?(delta?['percent']:[comparison.left.unit,comparison.right.unit]):temporal?(delta?['percent']:[selected[0].unit,selected[0].unit]):selected.map(b=>b.unit);
 return {rows,units,names};
}
export function WorkspacePlot(props:Props){const node=useRef<HTMLDivElement>(null);useEffect(()=>{if(!node.current)return;const chart=echarts.init(node.current,undefined,{renderer:'svg'});const {rows,units,names}=projection(props);const axes=units.length?[...new Set(units)]:[''];const labels=metricNames[props.locale];chart.setOption({animation:false,aria:{enabled:true},backgroundColor:'transparent',textStyle:{color:'#b7b8be'},legend:{textStyle:{color:'#b7b8be'}},tooltip:{trigger:'axis',renderMode:'richText'},grid:{left:75,right:75,bottom:65,top:45},xAxis:{type:'category',data:rows.map(r=>r.label+' · '+r.dates)},yAxis:axes.map((unit,i)=>({type:'value',name:workspaceUnit(props.locale,unit),position:i===0?'left':'right',splitLine:{lineStyle:{color:'#34353a'}}})),series:units.map((unit,i)=>({name:`${labels[names[i]??names[0]]??""} · ${i===1&&props.comparison?.mode==="temporal"?(props.locale==="ru"?"Год назад":"Prior year"):i+1} · ${unit}`,type:'line',yAxisIndex:axes.indexOf(unit),data:rows.map(r=>r.values[i]??null),connectNulls:false,lineStyle:{color:i===0?'#66b9d3':'#d2ac72'},itemStyle:{color:i===0?'#66b9d3':'#d2ac72'}}))});const observer=new ResizeObserver(()=>chart.resize());observer.observe(node.current);return()=>{observer.disconnect();chart.dispose();};},[props.definition,props.bindings,props.results,props.comparison,props.locale,props.legacy]);return <div ref={node} className="mw-plot" role="img" aria-label={props.locale==='ru'?'График серверных значений. Полные данные доступны в таблице.':'Server value chart. Complete data is available in the table.'}/>;}
export function WorkspaceTable(props:Props){const {rows,units}=projection(props);const ru=props.locale==='ru';return <div className="mw-table" tabIndex={0} role="region" aria-label={ru?'Таблица результатов':'Result table'}><table><caption>{ru?'Проверенные значения сервера':'Verified server values'} · UTC</caption><thead><tr><th scope="col">{ru?'Период':'Period'}</th><th scope="col">{ru?'Точные даты':'Exact dates'}</th>{units.map((u,i)=><th key={i} scope="col">{i+1} · {u}</th>)}<th scope="col">Δ</th><th scope="col">Δ %</th><th scope="col">{ru?'Состояние / причины':'State / reasons'}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><th scope="row">{r.label}</th><td>{r.dates}</td>{r.values.map((v,i)=><td key={i} data-value={v??''}>{v==null?'—':new Intl.NumberFormat(props.locale,{maximumFractionDigits:units[i]==='receipt'?0:2}).format(Number(v))}</td>)}<td data-value={r.absolute??''}>{r.absolute==null?'—':new Intl.NumberFormat(props.locale,{maximumFractionDigits:2}).format(Number(r.absolute))}</td><td data-value={r.relative??''}>{r.relative==null?'—':new Intl.NumberFormat(props.locale,{maximumFractionDigits:2}).format(Number(r.relative))}</td><td>{workspaceReason(props.locale,r.state)} {r.partial?(ru?'Часть периода':'Partial bucket'):''} {r.reasons.map(code=>workspaceReason(props.locale,code)).join(', ')}</td></tr>)}</tbody></table>{rows.length===0&&<p>{ru?'Нет применённых данных':'No applied data'}</p>}</div>;}
