\set ON_ERROR_STOP on

GRANT CONNECT ON DATABASE northwind_retail TO demo_reader;
GRANT USAGE ON SCHEMA retail TO demo_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA retail TO demo_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA retail GRANT SELECT ON TABLES TO demo_reader;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE CREATE ON SCHEMA retail FROM demo_reader;
