import {test,expect} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve(__dirname,'../../..');
const evidence=resolve(root,'.codex/delivery/evidence/MS-003/MS-003-pilot-native/browser');mkdirSync(evidence,{recursive:true});
for(const locale of ['ru','en'])test(`source document and real API ${locale}`,async({page,context},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.type()+':'+m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(`HTTP ${r.status()}`);});
 const a=JSON.parse(readFileSync(resolve(root,'.runtime/development/383a7390af/ms003-s04-browser.json'),'utf8'));
 await page.goto('/auth/sign-in');await page.getByLabel('Workspace identifier').fill(a.workspace);await page.getByLabel('Email',{exact:true}).fill(a.email);await page.getByLabel('Password',{exact:true}).fill(a.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('link',{name:/Create sales report/}).click();
 const pilot=page.frameLocator('iframe');await expect(pilot.locator('#context-open')).toBeVisible();await pilot.locator('.title-row h1').fill('Native pilot API report');await pilot.locator('#context-open').click();
 await pilot.locator('#context-apply').click();await expect(page.locator('iframe')).toHaveAttribute('data-chart-ready','true');await expect(pilot.locator('#overview-chart svg')).toBeVisible();
 await pilot.locator('#view-menu-open').click();const saving=page.waitForResponse(r=>r.url().endsWith('/api/reports/')&&r.request().method()==='POST');await pilot.locator('#save-analysis-view').click();const saved=await(await saving).json();await expect(page).not.toHaveURL(/new\/edit/);await expect(pilot.locator('#overview-chart svg')).toBeVisible();
 if(locale==='ru'){await pilot.locator('#view-menu-open').click();await pilot.locator('#locale-toggle').click();await pilot.locator('#view-menu-open').click();}
 await expect(pilot.locator('.kpi')).toHaveCount(8);await expect(pilot.locator('.kpi-value').nth(2)).toHaveText('—');
 const source=await context.newPage();await source.goto('http://127.0.0.1:8834/ru/source.html');
 // The production document is the source document with executable scripts removed.
 expect(await pilot.locator('style').textContent()).toBe(await source.locator('style').textContent());
 const symbols=(el:Element)=>{const copy=el.cloneNode(true) as Element;copy.querySelectorAll('*').forEach(n=>Array.from(n.attributes).filter(a=>a.name.startsWith('data-ui-')).forEach(a=>n.removeAttribute(a.name)));return copy.innerHTML;};expect(await pilot.locator('svg.sr-only').evaluate(symbols)).toBe(await source.locator('svg.sr-only').evaluate(symbols));
 for(const selector of ['.workspace','.page-header','.report-navigation-row','.kpi-module','#overview-visual-panel .panel-header']){
  const actual=await pilot.locator(selector).boundingBox();const target=await source.locator(selector).boundingBox();expect(actual).not.toBeNull();expect(target).not.toBeNull();for(const key of ['x','y','width','height'] as const)expect(Math.abs(actual![key]-target![key]),selector+'.'+key).toBeLessThanOrEqual(2);
 }
 await expect.poll(async()=> (await pilot.locator('#lifecycle-table td[data-metric=net_revenue]').first().boundingBox())?.width??0).toBeGreaterThanOrEqual(90);
 await page.screenshot({path:`${evidence}/report-${info.project.name}-${locale}.png`});if(locale==='ru')await source.screenshot({path:`${evidence}/source-${info.project.name}.png`});await source.close();
 await pilot.locator('#trust-open').click();await expect(pilot.locator('#trust-dialog')).toContainText('14995 / 15000');if(locale==='ru')await page.screenshot({path:`${evidence}/trust-${info.project.name}.png`});await pilot.locator('#trust-dialog [data-dialog-close]').first().click();
 const focus=pilot.locator('[data-focus-open=overview]').first();await focus.focus();await page.keyboard.press('Enter');await expect(pilot.locator('#focus-surface')).toBeVisible();await expect(pilot.locator('#focus-table td[data-metric=net_revenue]')).toHaveCount(saved.result.daily.length);await expect(pilot.locator('#focus-table td[data-metric=net_revenue]').first()).toHaveAttribute('data-value',saved.result.daily[0].net_revenue);await page.keyboard.press('Escape');await expect(focus).toBeFocused();if(locale==='ru'){await focus.click();await page.screenshot({path:`${evidence}/focus-${info.project.name}.png`});await page.keyboard.press('Escape');}
 await pilot.locator('[data-view-button=overview][data-view=table]').click();await expect(pilot.locator('#overview-chart-table td[data-metric=net_revenue]')).toHaveCount(saved.result.daily.length);
 await pilot.locator('#period-menu-open').click();await pilot.locator('[data-period-grain=month]').click();await pilot.locator('[data-period-value="2025-11"]').click();
 await pilot.locator('#stores-menu-open').click();await expect(pilot.locator('[data-store-option]').first()).toBeVisible();await pilot.locator('[data-store-option]').first().check();await page.keyboard.press('Escape');
 await pilot.locator('#comparison-menu-open').click();await pilot.locator('[data-quick-comparison][value="2024"]').check();await page.keyboard.press('Escape');
 const computed=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/analytics/sales-reports/v1'));await pilot.locator('#context-open').click();await pilot.locator('#context-apply').click();const filtered=await(await computed).json();expect(filtered.parameters.period.starts_on).toBe('2025-11-01');expect(filtered.parameters.store_id).toBeTruthy();expect(filtered.parameters.comparison).toBe('previous_year_same_dates');
 await pilot.locator('#view-menu-open').click();const persisted=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/versions'));await pilot.locator('#save-analysis-view').click();await persisted;await page.keyboard.press('Escape');
 await pilot.locator('#context-open').click();await pilot.locator('[data-inspector-tab=saved]').click();await pilot.locator('#published-analysis-view-row').click();await expect(page).toHaveURL(/snapshots/);let runs=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('sales-reports'))runs++;});await page.reload();await expect(pilot.locator('#overview-chart svg')).toBeVisible();expect(runs).toBe(0);
 await page.evaluate(()=>document.documentElement.style.zoom='2');await expect(pilot.locator('#context-open')).toBeVisible();expect(errors).toEqual([]);
});
test('native controls preserve CAS, storage failure, restart and denial boundaries',async({page,context,request})=>{
 const a=JSON.parse(readFileSync(resolve(root,'.runtime/development/383a7390af/ms003-s04-browser.json'),'utf8'));
 await page.goto('/auth/sign-in');await page.getByLabel('Workspace identifier').fill(a.workspace);await page.getByLabel('Email',{exact:true}).fill(a.email);await page.getByLabel('Password',{exact:true}).fill(a.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('link',{name:/Create sales report/}).click();
 const p=page.frameLocator('iframe');await p.locator('#context-open').click();await p.locator('#context-apply').click();await expect(page.locator('iframe')).toHaveAttribute('data-chart-ready','true');await p.locator('#view-menu-open').click();await p.locator('#save-analysis-view').click();await expect(page).not.toHaveURL(/new\/edit/);const editor=page.url();
 const other=await context.newPage();await other.goto(editor);const q=other.frameLocator('iframe');await q.locator('.title-row h1').fill('Concurrent real title');await q.locator('#view-menu-open').click();const changed=other.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/versions'));await q.locator('#save-analysis-view').click();await changed;await other.close();
 await p.locator('.title-row h1').fill('Keep this unsaved title');await p.locator('#view-menu-open').click();await p.locator('#save-analysis-view').click();await expect(p.locator('#saved-view-status')).toContainText('newer draft');await expect(p.locator('.title-row h1')).toHaveText('Keep this unsaved title');await page.keyboard.press('Escape');await p.locator('#context-open').click();await p.locator('#context-reset').click();await expect(p.locator('.title-row h1')).toHaveText('Concurrent real title');
 await p.locator('[data-inspector-tab=saved]').click();await p.locator('#published-analysis-view-row').click();await expect(page).toHaveURL(/snapshots/);const snapshot=new URL(page.url()).pathname.split('/')[6];
 expect((await request.post('http://127.0.0.1:58105/restart')).ok()).toBe(true);await expect.poll(async()=>{try{return(await request.get('/api/health/live')).status();}catch{return 0;}}).toBe(200);await page.reload();await expect(page.locator('iframe')).toHaveAttribute('data-chart-ready','true');
 expect((await request.post(`http://127.0.0.1:58105/artifact/${snapshot}/storage`)).ok()).toBe(true);try{await page.reload();await expect(page.getByRole('alert')).toContainText('unavailable');await expect(page.locator('iframe')).toHaveCount(0);}finally{await request.post(`http://127.0.0.1:58105/artifact/${snapshot}/restore`);}
 await page.goto(editor);await p.locator('#period-menu-open').click();await p.locator('[data-period-value="2023"]').click();await p.locator('#context-open').click();await p.locator('#context-apply').click();await expect(p.locator('.chart-summary').first()).toHaveText('No eligible receipts in this period.');
 await request.post('http://127.0.0.1:58105/expire');await p.locator('#context-open').click();await p.locator('#context-apply').click();await expect(page.getByRole('alert')).toContainText('session expired');await expect(page.locator('iframe')).toHaveCount(0);
});
