import {test,expect} from './observed-test';
import type {Page} from '@playwright/test';
async function login(page:Page,workspace:string){await page.addInitScript(()=>localStorage.setItem('custometry-language','en'));await page.goto('/auth/sign-in');await page.getByLabel(/Workspace/).fill(workspace);await page.getByLabel('Email',{exact:true}).fill('author@example.test');await page.getByLabel('Password',{exact:true}).fill('synthetic-author-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(/\/reports$/);}
test('real competing save retains the losing draft and empty scope is not zero',async({page,request,context},info)=>{
 const scenario=await(await request.get('/fixture/scenario')).json() as {workspace:string;report:string};await login(page,scenario.workspace);
 const url=`/w/${scenario.workspace}/reports/${scenario.report}/edit`;await page.goto(url);const f=page.frameLocator('iframe');await f.getByRole('button',{name:'Close inspector'}).click();
 await expect(f.locator('.mw-cards .kpi-value').first()).not.toHaveText('—');await f.getByRole('button',{name:'Apply',exact:true}).click();await expect(f.getByRole('button',{name:'Save report',exact:true})).toBeEnabled({timeout:60000});await f.getByRole('button',{name:'Save report',exact:true}).click();await expect(f.getByRole('status').filter({hasText:'Saved'})).toBeVisible({timeout:60000});
 const second=await context.newPage();await second.goto(url);const other=second.frameLocator('iframe');await other.getByRole('button',{name:'Close inspector'}).click();await expect(other.locator('.mw-cards .kpi-value').first()).not.toHaveText('—',{timeout:60000});
 await f.getByLabel('Report title',{exact:true}).fill('Winning revision');await f.getByRole('button',{name:'Save report',exact:true}).click();await expect(f.getByRole('status').filter({hasText:'Saved'})).toBeVisible({timeout:60000});
 await other.getByLabel('Report title',{exact:true}).fill('Retained losing draft');await other.getByRole('button',{name:'Save report',exact:true}).click();await expect(other.getByRole('alert')).toContainText('Version conflict',{timeout:60000});await expect(other.getByLabel('Report title',{exact:true})).toHaveValue('Retained losing draft');await second.screenshot({path:info.outputPath('conflict.png')});await second.close();
 await f.getByRole('button',{name:/2025-01-01.*Report context/}).click();await f.getByRole('group',{name:'Common stores',exact:true}).getByRole('checkbox',{name:'Inherit / all permitted'}).uncheck();await f.locator('.mw-inspector footer').getByRole('button',{name:'Apply',exact:true}).click();await expect(f.locator('.mw')).toHaveAttribute('aria-busy','false',{timeout:60000});await expect(f.getByRole('alert')).toHaveCount(0);await f.getByRole('button',{name:'Close inspector'}).click();await expect(f.locator('.mw-cards .kpi-value').first()).toHaveText('—',{timeout:60000});await expect(f.locator('.mw-cards').getByText(/No data/).first()).toBeVisible();
 await page.screenshot({path:info.outputPath('empty-scope.png')});
});
