import {test,expect} from './observed-test';
test.afterEach(async({page},info)=>{if(await page.locator('iframe').count()){await page.screenshot({path:info.outputPath('final.png')});}});
test('real workspace Apply, immutable Save, fiscal adoption and keyboard',async({page,request},info)=>{
 const scenario=await (await request.get('/fixture/scenario')).json() as {workspace:string;report:string};
 const calculationRequests:string[]=[];page.on('request',r=>{if(r.method()==='POST'&&/\/(apply|results)$/.test(new URL(r.url()).pathname))calculationRequests.push(new URL(r.url()).pathname);});
 const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.stack);});
 await page.addInitScript(()=>localStorage.setItem('custometry-language','ru'));
 await page.goto('/auth/sign-in');
 await page.getByLabel(/Идентификатор рабочего пространства|Workspace/).fill(scenario.workspace);
 await page.getByLabel(/Электронная почта|Email|Почта/).fill('author@example.test');
 await page.getByLabel(/Пароль|Password/).fill('synthetic-author-password');
 await page.getByRole('button',{name:/Войти|Sign in/}).click();
 await page.waitForURL(/\/reports$/);
 await page.goto(`/w/${scenario.workspace}/reports/${scenario.report}/edit`);
 const frame=page.frameLocator('iframe');
 await expect(frame.getByRole('heading',{name:'Инспектор отчёта'})).toBeVisible();
 await frame.getByRole('button',{name:'Закрыть инспектор'}).click();
 await frame.getByRole('button',{name:'Применить',exact:true}).click();
 await expect(frame.getByRole('button',{name:'Сохранить отчёт'})).toBeEnabled({timeout:60000});
 await frame.getByRole('button',{name:'Сохранить отчёт'}).click();
 await expect(frame.getByRole('status').filter({hasText:'Сохранено'})).toBeVisible({timeout:60000});
 await frame.getByRole('button',{name:'Таблица',exact:true}).last().click();
 await expect(frame.getByRole('table').filter({hasText:'Проверенные значения сервера'})).toBeVisible();
 await frame.getByRole('button',{name:'Focus',exact:true}).click();
 await expect(frame.getByRole('dialog',{name:'Focus'})).toBeVisible();
 await page.keyboard.press('Escape');
 await expect(frame.getByRole('button',{name:'Focus',exact:true})).toBeFocused();
 await frame.getByLabel('Название отчёта',{exact:true}).fill('S04 display-only saved');
 await expect(frame.getByRole('button',{name:'Сохранить отчёт'})).toBeEnabled();
 await frame.getByRole('button',{name:'Сохранить отчёт'}).click();
 await expect(frame.getByRole('status').filter({hasText:'Сохранено'})).toBeVisible({timeout:60000});
 const priorValue=await frame.locator('.mw-cards .kpi-value').first().innerText();const beforeReload=calculationRequests.length;
 await page.reload();
 await expect(frame.getByLabel('Название отчёта',{exact:true})).toHaveValue('S04 display-only saved');
 await frame.getByRole('button',{name:'Закрыть инспектор'}).click();
 await expect(frame.locator('.mw-cards .kpi-value').first()).toHaveText(priorValue,{timeout:60000});expect(priorValue).not.toBe('—');
 await frame.getByRole('button',{name:'Таблица',exact:true}).last().click();await expect(frame.locator('.mw-table tbody tr')).toHaveCount(31);expect(calculationRequests.length).toBe(beforeReload);
 await frame.getByRole('button',{name:'График',exact:true}).last().click();
 await page.screenshot({path:info.outputPath('workspace.png')});
 await frame.getByRole('button',{name:'Точный снимок',exact:true}).click();await page.waitForURL(/\/snapshots\//);await expect(frame.locator('.mw-cards .kpi-value').first()).toHaveText(priorValue,{timeout:60000});expect(calculationRequests.length).toBe(beforeReload);
 expect(errors).toEqual([]);
});

test('workset catalog, copy, six grains, comparison and fiscal default',async({page,request},info)=>{
 const scenario=await(await request.get('/fixture/scenario')).json() as {workspace:string;report:string};
 await page.addInitScript(()=>localStorage.setItem('custometry-language','ru'));
 await page.goto('/auth/sign-in');await page.getByLabel('Идентификатор рабочего пространства').fill(scenario.workspace);await page.getByLabel('Электронная почта').fill('author@example.test');await page.getByLabel('Пароль',{exact:true}).fill('synthetic-author-password');await page.getByRole('button',{name:'Войти',exact:true}).click();await page.waitForURL(/\/reports$/);
 await page.goto(`/w/${scenario.workspace}/reports/${scenario.report}/edit`);const f=page.frameLocator('iframe');
 await expect(f.getByRole('heading',{name:'Инспектор отчёта'})).toBeVisible();
 await f.getByText('Каталог метрик',{exact:true}).click();await f.getByLabel('Поиск метрики').fill('Выручка');await expect(f.locator('.mw-inspector details').getByRole('button',{name:'Выручка',exact:true})).toBeEnabled();await f.getByLabel('Поиск метрики').focus();await page.keyboard.press('Tab');await page.keyboard.press('Enter');
 await expect(f.locator('.mw-cards .kpi-card')).toHaveCount(4);
 await f.getByRole('button',{name:'Карточка выше'}).last().focus();await page.keyboard.press('Enter');
 await f.locator('.mw-cards .kpi-card').first().getByLabel('Выбрать',{exact:true}).check();await f.getByRole('button',{name:'Копировать набор'}).click();await expect(f.locator('.mw-cards input:checked')).toHaveCount(0);await expect(f.getByRole('group',{name:'Наборы'}).getByRole('button',{name:'Показатели',exact:true})).toHaveCount(2);
 await f.getByRole('button',{name:'Закрыть инспектор'}).click();
 await f.getByRole('button',{name:/2025-01-01.*Контекст отчёта/}).click();
 for(const grain of ['week','month','quarter','half_year','year','day']){await f.getByRole('combobox',{name:'Детализация',exact:true}).selectOption(grain);await f.locator('.mw-inspector footer').getByRole('button',{name:'Применить'}).click();await expect(f.locator('.mw')).toHaveAttribute('aria-busy','false',{timeout:60000});await expect(f.getByRole('alert')).toHaveCount(0);}
 await f.getByRole('button',{name:'Закрыть инспектор'}).click();
 await f.locator('.mw-cards .kpi-card').nth(0).getByLabel('Выбрать',{exact:true}).check();await f.locator('.mw-cards .kpi-card').nth(1).getByLabel('Выбрать',{exact:true}).check();
 await f.getByRole('button',{name:'Настроить график / сравнение'}).click();await f.getByRole('button',{name:'Сравнить две карточки'}).click();await expect(f.locator('.mw')).toHaveAttribute('aria-busy','false',{timeout:60000});await f.getByRole('button',{name:'Закрыть инспектор'}).click();
 await f.getByText('Настройки компании · финансовый год',{exact:true}).click();await f.getByRole('combobox',{name:'Месяц начала',exact:true}).selectOption('4');const pin=await f.locator('p').filter({hasText:'Закреплённый календарь:'}).locator('code').innerText();await f.getByRole('button',{name:'Сохранить календарь компании'}).click();await expect(f.getByRole('status').filter({hasText:'Календарь сохранён'})).toBeVisible();await expect(f.locator('p').filter({hasText:'Закреплённый календарь:'}).locator('code')).toHaveText(pin);await f.getByRole('button',{name:'Принять календарь компании'}).click();
 await expect(f.getByRole('button',{name:'Сохранить отчёт'})).toBeDisabled();await f.getByRole('button',{name:'Применить',exact:true}).click();await expect(f.locator('.mw')).toHaveAttribute('aria-busy','false',{timeout:60000});await expect(f.getByRole('button',{name:'Сохранить отчёт'})).toBeEnabled({timeout:60000});await f.getByRole('button',{name:'Сохранить отчёт'}).click();await expect(f.getByRole('status').filter({hasText:'Сохранено'})).toBeVisible({timeout:60000});
 await f.getByRole('button',{name:'Таблица',exact:true}).last().click();await expect(f.locator('.mw-table thead')).toContainText('receipt');await expect(f.locator('.mw-table tbody tr')).toHaveCount(31);await f.getByRole('button',{name:'График',exact:true}).last().click();
 await f.getByRole('button',{name:'Настроить набор'}).focus();await page.keyboard.press('Enter');await page.keyboard.press('Escape');await expect(f.getByRole('button',{name:'Настроить набор'})).toBeFocused();await page.keyboard.press('Enter');await page.screenshot({path:info.outputPath('inspector.png')});await f.getByRole('button',{name:'Закрыть инспектор'}).click();
 await page.setViewportSize({width:400,height:900});await page.screenshot({path:info.outputPath('reflow-400.png')});await expect(f.getByRole('button',{name:'Применить',exact:true})).toBeInViewport();
});
