import {test, expect, type Page} from '@playwright/test';
import {readFileSync, writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve(__dirname,'../../..');
const evidence=resolve(root,'.codex/delivery/evidence/MS-003/MS-003-S04-correction/browser');
const access=()=>JSON.parse(readFileSync(resolve(root,'.runtime/development/383a7390af/ms003-s04-browser.json'),'utf8'));
async function locale(page:Page,ru:boolean){if(ru){await page.getByRole('button',{name:'Profile',exact:true}).click();await page.getByRole('button',{name:'Русский',exact:true}).click();await page.getByRole('button',{name:'Закрыть меню раздела'}).click();}}
async function login(page:Page,ru=false){const a=access();await page.goto('/auth/sign-in');await page.getByLabel('Workspace identifier').fill(a.workspace);await page.getByLabel('Email',{exact:true}).fill(a.email);await page.getByLabel('Password',{exact:true}).fill(a.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Report library'})).toBeVisible();await locale(page,ru);}
async function create(page:Page,ru=false){await page.getByRole('link',{name:new RegExp(ru?'Создать отчёт':'Create sales report')}).click();await expect(page.getByLabel(ru?'Источник':'Source',{exact:true})).not.toHaveValue('');await page.getByLabel(ru?'Название отчёта':'Report title').fill(ru?'Продажи по чекам':'Receipt sales');await page.locator('.drawer-footer').getByRole('button',{name:ru?'Применить':'Apply',exact:true}).click();await expect(page.locator('[data-chart-ready=true]')).toBeVisible();const saved=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/reports/'));await page.locator('.drawer-footer').getByRole('button',{name:ru?'Сохранить':'Save',exact:true}).click();const result=await(await saved).json();await expect(page).not.toHaveURL(/new\/edit/);await expect(page.locator('[data-chart-ready=true]')).toBeVisible();return result;}
const dimensions=async(page:Page,source=false)=>page.evaluate(source=>{
 const selectors={workspace:'.workspace',header:'.page-header',tabs:'.report-navigation-row',intro:'.page-intro',kpi:'.kpi-module',panel:'#overview-visual-panel',panelHeader:'#overview-visual-panel .panel-header',rail:source?'.sidebar':'.pilot-sidebar',inspector:'.context-drawer'};
 return Object.fromEntries(Object.entries(selectors).map(([key,selector])=>{const el=document.querySelector(selector)!;const r=el.getBoundingClientRect();const s=getComputedStyle(el);return[key,{x:r.x,y:r.y,width:r.width,height:r.height,bg:s.backgroundColor,radius:s.borderRadius,font:s.fontFamily,fontSize:s.fontSize}];}));
},source);
for(const ru of [true,false])test(`pilot structure and real journey ${ru?'ru':'en'}`,async({page,context},info)=>{
 const failures:string[]=[];page.on('pageerror',()=>failures.push('pageerror'));page.on('console',m=>{if(['error','warning'].includes(m.type()))failures.push(m.type());});page.on('response',r=>{if(r.status()>=400)failures.push(String(r.status()));});
 await login(page,ru);const saved=await create(page,ru);
 const source=await context.newPage();await source.goto('http://127.0.0.1:8834/ru/source.html');if(!ru){await source.locator('#view-menu-open').click();await source.locator('#locale-toggle').click();await source.keyboard.press('Escape');}
 const target=await dimensions(source,true);const actual=await dimensions(page);
 // Compare shared composition against the live preserved source, not a new golden.
 for(const key of ['workspace','header','tabs','intro','kpi','panelHeader','rail'])for(const property of ['x','y','width','height'] as const){
  // Header text wrapping depends on locale; the shared box must still be identical.
  expect(Math.abs(actual[key][property]-target[key][property]),`${key}.${property}`).toBeLessThanOrEqual(2);
 }
 for(const key of ['workspace','header','tabs','kpi','panelHeader'])for(const property of ['bg','radius','font','fontSize'] as const)expect(actual[key][property],`${key}.${property}`).toEqual(target[key][property]);
 await page.screenshot({path:`${evidence}/report-${info.project.name}-${ru?'ru':'en'}.png`});
 if(ru)await source.screenshot({path:`${evidence}/pilot-${info.project.name}.png`});
 await page.getByRole('button',{name:ru?'Доверие к результату':'Result trust',exact:true}).click();await expect(page.getByRole('dialog').getByText('14995 / 15000',{exact:true})).toBeVisible();if(ru)await page.screenshot({path:`${evidence}/trust-dialog-${info.project.name}.png`});await page.keyboard.press('Escape');await page.getByRole('button',{name:ru?'Настройки отчёта':'Report settings'}).click();await page.getByRole('tab',{name:ru?'Доверие':'Trust',exact:true}).click();await source.locator('#context-open').click();await source.locator('[data-inspector-tab=trust]').click();
 const openActual=await dimensions(page);const openTarget=await dimensions(source,true);for(const property of ['x','y','width','height'] as const)expect(Math.abs(openActual.inspector[property]-openTarget.inspector[property]),`inspector.${property}`).toBeLessThanOrEqual(2);
 if(ru){await page.screenshot({path:`${evidence}/trust-${info.project.name}.png`});await source.screenshot({path:`${evidence}/pilot-trust-${info.project.name}.png`});writeFileSync(`${evidence}/geometry-${info.project.name}.json`,JSON.stringify({closed:{source:target,implementation:actual},open:{source:openTarget,implementation:openActual}},null,2));}
 await source.close();await page.keyboard.press('Escape');await expect(page.locator('.context-drawer')).not.toBeVisible();
 await page.getByRole('button',{name:ru?'Таблица':'Table',exact:true}).click();await expect(page.locator('tbody tr')).toHaveCount(saved.result.daily.length);await expect(page.locator('tbody tr').first().locator('td').first()).toHaveAttribute('data-value',saved.result.daily[0].net_revenue);
 if(ru)await page.screenshot({path:`${evidence}/table-${info.project.name}.png`});
 const focus=page.getByRole('button',{name:ru?'Развернуть график и таблицу':'Expand chart and table'});await focus.focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();if(ru)await page.screenshot({path:`${evidence}/focus-${info.project.name}.png`});await page.keyboard.press('Escape');await expect(focus).toBeFocused();
 await page.getByRole('button',{name:ru?'Период':'Period',exact:true}).click();await page.getByRole('dialog').getByLabel(ru?'С':'From',{exact:true}).fill('2025-02-01');await page.getByRole('dialog').getByLabel(ru?'По':'To',{exact:true}).fill('2025-03-01');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:ru?'Магазин':'Store',exact:true}).click();await page.getByRole('dialog').getByLabel(ru?'Магазин':'Store',{exact:true}).selectOption({index:1});await page.keyboard.press('Escape');
 await page.getByRole('button',{name:ru?'Сравнение':'Comparison',exact:true}).click();await page.getByRole('dialog').getByLabel(ru?'Сравнение':'Comparison',{exact:true}).selectOption('previous_year_same_dates');await page.getByRole('dialog').getByRole('button',{name:ru?'Применить':'Apply',exact:true}).click();await expect(page.getByRole('dialog').getByRole('button',{name:ru?'Применить':'Apply',exact:true})).toBeEnabled();await page.keyboard.press('Escape');
 await page.getByRole('button',{name:ru?'Вид отчёта':'Report view'}).click();await page.getByRole('dialog').getByRole('button',{name:ru?'Сохранить':'Save',exact:true}).click();await expect(page.getByRole('dialog').getByRole('button',{name:ru?'Сохранить':'Save',exact:true})).toBeEnabled();
 let computations=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/analytics/sales-reports/v1'))computations++;});await page.getByRole('link',{name:ru?'Открыть точный предпросмотр':'Open exact draft preview'}).click();await page.reload();await expect(page.locator('[data-chart-ready=true]')).toBeVisible();expect(computations).toBe(0);
 await page.evaluate(()=>document.documentElement.style.zoom='2');await page.getByRole('button',{name:ru?'Таблица':'Table',exact:true}).click();await expect(page.locator('table').first()).toBeVisible();if(ru)await page.screenshot({path:`${evidence}/zoom-${info.project.name}.png`});expect(failures).toEqual([]);
});
test('CAS, immutable restart, unavailable artifact, empty data and session expiry',async({page,context,request})=>{
 await login(page);await create(page);const editor=page.url();const other=await context.newPage();await other.goto(editor);await other.getByRole('button',{name:'Report settings'}).click();await other.getByLabel('Report title').fill('Concurrent title');await other.locator('.drawer-footer').getByRole('button',{name:'Save',exact:true}).click();await expect(other.getByText('Saved draft',{exact:true})).toHaveCount(1);await other.close();
 await page.getByRole('button',{name:'Report settings'}).click();await page.getByLabel('Report title').fill('Retained unsaved title');await page.locator('.drawer-footer').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('alert')).toContainText('newer draft');await expect(page.getByLabel('Report title')).toHaveValue('Retained unsaved title');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Reload saved draft'}).click();await expect(page.getByRole('alert')).toHaveCount(0);await page.getByRole('button',{name:'Report view'}).click();await page.getByRole('link',{name:'Open exact draft preview'}).click();await expect(page).toHaveURL(/snapshots/);const exact=page.url();
 await request.post('http://127.0.0.1:58105/restart');await expect.poll(async()=>{try{return (await request.get('/api/health/live')).status();}catch{return 0;}}).toBe(200);await page.reload();await expect(page.locator('[data-chart-ready=true]')).toBeVisible();const sid=new URL(exact).pathname.split('/')[6];expect((await request.post(`http://127.0.0.1:58105/artifact/${sid}/storage`)).ok()).toBe(true);try{await page.reload();await expect(page.getByRole('alert')).toContainText('unavailable');await expect(page.locator('.report-metrics')).toHaveCount(0);}finally{await request.post(`http://127.0.0.1:58105/artifact/${sid}/restore`);}
 await page.goto(editor);await page.getByRole('button',{name:'Period',exact:true}).click();await page.getByRole('dialog').getByLabel('From',{exact:true}).fill('2023-01-01');await page.getByRole('dialog').getByLabel('To',{exact:true}).fill('2023-01-02');await page.getByRole('dialog').getByRole('button',{name:'Apply',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByText('No eligible receipts in this period.')).toBeVisible();
 await request.post('http://127.0.0.1:58105/expire');await page.getByRole('button',{name:'Period',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByRole('alert')).toContainText('session expired');await expect(page.locator('.report-metrics')).toHaveCount(0);
});
